'use strict';

const DINE_MINA = [
  '<p>Mina eats at the far end of the table, laptop open beside her tray, a protein shake and a piece of fruit in front of her. She eats precisely, methodically, like she’s following a protocol, and she’s the only one at the table who hasn’t touched the dessert cups. “Whey isolate,” she says, holding up a small blue cup she’s fished from someone’s tray. “Flavored. Nothing weird.” She sets it down, doesn’t drink it, and goes back to her notes. You notice she keeps a little notebook in her bag now. You notice she writes in it whenever someone else takes a sip.</p>',
  '<p>Mina eats the same breakfast she always has, but there are two pastries now, and then a third, and she eats them while she reads, one hand moving to her mouth without her attention. Her jeans are snugger at the waist, and she has to unbutton them at the table — she does it quickly, looking down, then looks up and catches you watching. “It’s the syrup,” she says, too fast. “The dosing is in the syrup.” She says it like it’s a theory she’s testing. Her hand is already on the next pastry.</p>',
  '<p>Mina eats more than she means to, and she knows it, and it’s written all over her face — the little frown between bites, the way she puts the fork down and picks it back up. Her belly rounds against the table, soft and undeniable, and she keeps looking at it like it’s an experiment that’s produced an impossible result. “I haven’t changed anything,” she says, to no one, to the tray. It’s the truest thing she’s said all semester, and she can’t hear it. She eats another bite. The fork goes back up to her mouth.</p>',
  '<p>Mina doesn’t bring the laptop anymore. She brings the tray, and then the second tray, and she eats with a slow, defeated precision, her belly resting heavy in her lap, her face round and soft above it. She’s stopped arguing. “The numbers don’t close,” she says, around a mouthful, and her voice is level and clinical and utterly finished. She reaches for the dessert cup, and then for the one on your tray, and she eats them both, and she doesn’t write anything down. Mina has stopped taking notes. Something ends quietly at the table, and neither of you says it.</p>',
  '<p>Mina is vast now, and she’s stopped pretending otherwise. She sits on the wide scooter seat, her belly a mountain in her lap, and the drone brings the spoon to her mouth and she takes it without ceremony, chewing, swallowing, her sharp eyes fixed on the window like she’s still watching for something. She isn’t. There’s nothing left to watch for. When she burps, low and wet, she doesn’t even pause. “Efficient,” she says, and it’s the last word she says for a long time, and the drone presses the next bite forward, and she takes it.</p>',
  '<p>Mina doesn’t sit at the far end of the table anymore — she can’t, the benches are too close — so she sits at the end table by the window, and the drone brings her trays three at a time. She eats with a dreamy, unhurried patience, her belly resting heavy and soft in her lap, crumbs on her chin, and she doesn’t open the laptop, doesn’t reach for the notebook, doesn’t do anything but eat and watch the light move across the floor. “I’m not going to figure it out,” she says once, not looking at you, and she says it like she’s relieved. The drone presses the next bite forward. She takes it.</p>',
  '<p>Mina is enormous, and the commons has made a space for her. She sits on the scooter at the end table, a mountain of soft flesh in a wide white seat, and the drone feeds her between long, contented swallows — pastries, bacon, something sweet — and she lets out a low burp without even looking up. “The data was right,” she says, and it comes out warm and satisfied, and she smiles at you, slow and heavy and utterly at peace. She is so happy. That’s the worst part. She is so, so happy, and the tray is already coming back, and she opens her mouth without being asked.</p>',
  '<p>Mina is enormous, and she still makes it to the commons every meal — it’s the one thing she still does for herself. The scooter carries her to the end table by the window, and the drone feeds her, and she eats with the same dreamy patience, watching the light move across the floor. She doesn’t open the laptop anymore. She doesn’t take notes. She eats, and she watches, and she is still here — which, at her size, is its own small defiance.</p>',
  '<p>Mina doesn’t come to the commons anymore — she can’t, not really; the scooter can’t manage the doors and the tables are too close together. A drone brings her tray to the doorway of the room and comes back for it empty, and the sound that carries down the hall now isn’t just the drone — it’s her, eating and moaning, greedy and shameless, a low animal pleasure that the whole floor has learned to live around. Sometimes the door is ajar and you catch her: naked in the wreckage of the feast, one hand in the tray and one hand between her thighs, her hips rolling, a long wet moan rising between mouthfuls — “efficient, good, more” — her voice thick and sticky, still cataloguing her own ruin. There’s an empty place at the end table where she used to sit, and nobody sits in it, and nobody mentions it. Whatever Mina is doing up there, the room knows, and the campus knows, and the knowing is as warm and accepted as everything else here.</p>'
];
