'use strict';

function minaZolaMorn(mt){
  if (mt <= 2){
    return '<p>Mina is awake before the alarm — she always was — but now she’s not at her desk. She’s sitting on the edge of her bed, holding her phone, and the screen is a text thread with a single contact: ZOLA, in caps. She looks up when you stir and says, without preamble, “She ran the numbers on me. She knows my intake better than I do.” Her voice is flat, but there’s a tremor under it — not fear. Something else. “She says I’m efficient. She says I’m the best subject she’s ever had.” She looks back at the phone, and a slow, involuntary smile cracks the precision of her face. “She says she wants to see me grow.”</p>' +
      '<p>Mina eats breakfast at the commons now — at Zola’s table — and she comes back with her notebook empty and her cheeks flushed, and she won’t look at you directly. “She explained the dosing,” she says finally, voice tight. “It’s not in the syrup. It’s in the wanting. She wants me to eat, so I want to eat, and then I eat, and then—” She stops. “It’s a closed loop.” She says it the way she used to say pH strip — clinically, defensively — but her hand is already reaching for the pastry, and her eyes are soft, and you understand that the analysis is over, and the surrender has begun.</p>';
  }
  if (mt <= 5){
    return '<p>Mina is on her bed, and the notebook is gone from the nightstand — replaced by a tray she didn’t touch until she was halfway awake. She eats, and she moans softly, and she doesn’t apologize for it. “Zola says I’m past the control phase,” she says, mouth full, and her eyes are warm and glazed. “She says the data’s conclusive. I’m hers now.” She says the word hers like it’s the answer to every equation she ever stopped running, and she says it with a peace that wasn’t there when she still believed she could win.</p>' +
      '<p>Mina is at the commons most of the day, at Zola’s table. She comes back heavy, slow, happy, smelling like glaze and warm syrup, and she talks about Zola the way she used to talk about her thesis — with rigor, with devotion, with the flat certainty of someone who has finished a study and accepted the result. “She records everything,” Mina says, dreamy. “She knows when I breathe. She knows when I want. She says I’m the best data she’s ever collected.” She pats the soft weight of her belly, possessive. “I believe her. I am her best data.”</p>';
  }
  return '<p>Mina doesn’t get up for breakfast anymore. Zola comes to her — the enormous woman wheels in on her scooter, a tray across her lap, and feeds Mina by hand, cooing, cataloguing every swallow out loud. “Efficient. Good. More,” Zola murmurs, and Mina repeats the words like a subject being trained, moaning around the bites, her eyes half-closed, her body a vast warm mountain under the sheet. “She says I’m the result,” Mina sighs, dreamy, hips rolling. “She says the experiment worked. I am the result.” She says it like it’s the proudest sentence she has ever produced, and maybe it is.</p>' +
      '<p>Mina is enormous now, and she is Zola’s, and the two are not separate facts. She lies in her bed, buried in pillows, and she speaks in Zola’s cadences, Zola’s certainties, the flat calm of a machine that has accepted its program. “Mama Zola says I don’t need to analyze anymore,” she says, dreamy, one hand in the tray and one between her thighs. “She says the analysis was always going to end here. She was right. She’s always right about me.” She moans, soft and happy, and the drone hums in the hall, and somewhere in the commons Zola is eating, patient, waiting for her girl.</p>';
}

function minaCourtingMorn(left, mt){
  if (left <= 3){
    return '<p>Mina is at her desk, and she’s not studying — she’s writing. A card, in her precise handwriting, with a single contact at the top: ZOLA. She looks up when you stir and doesn’t hide it. “She asked about my data,” she says, flatly, and there’s a crack in her voice, like something is opening. “She said she’s never met a girl who tracks her own intake so carefully. She said she wants to see my notes.” She sets the pen down. “She says I’m the most interesting subject she’s ever seen.” She doesn’t say it like she’s worried. She says it like she’s been waiting to be found.</p>';
  }
  if (mt <= 4){
    return '<p>Mina is dressed and at the door before the rest of you wake — a first, for her, who used to be the last one moving. “Commons,” she says, and she says it like a hypothesis she’s testing. “Zola asked to see me. She says she has questions about my intake curve.” She holds her notebook against her chest, and her cheeks are faintly pink. “She thinks I’m doing something right.” She’s gone before you can answer, and the notebook — the one she never lets anyone touch — is in her hands, and it’s headed for the commons.</p>';
  }
  return '<p>Mina is at her desk with her phone out, and she’s talking to someone — quietly, in a voice you’ve never heard her use, slower and warmer. She catches you looking and sets the phone down, and for a second she almost smiles. “Zola. From the commons.” She says the name carefully, like it’s a variable she hasn’t finished solving. “She said she’s been watching me. She said I weigh my food like a scientist, and she wants to know why.” She pauses. “She says she thinks I’m wasting myself on small portions.” She looks at the phone again, then away. “She’s… not wrong.”</p>';
}

const MINA_MORN = [
  [
    '<p>Mina is the first one up, always, and she’s already dressed when the rest of you are still swimming up out of sleep. She’s small and precise, compact — narrow shoulders, a flat stomach visible between the hem of her shirt and the top of her jeans, small high breasts, a face that reads like it’s already finished a test you haven’t started. She’s at her desk with a laptop, a cup of black coffee, and a highlighter, and she looks exactly like a pre-med student who has decided not to be touched by anything that happens on this campus. She doesn’t say good morning. She says, “The peptide lab is doing an open house Thursday.” That’s her version of good morning.</p>',
    '<p>Getting dressed for Mina is a study in efficiency: jeans in one pull, shirt over her head, a quick finger-comb of her hair, and she’s done — total, maybe, ninety seconds. She doesn’t check herself in the mirror. She doesn’t need to; she knows exactly what she is. Her body is a machine she maintains, lean and hard-edged and unremarkable. She stands, picks up her bag, and pauses at the door. “I’ll be back for dinner.” She looks at you both for a second, and there’s something almost soft in it. “Try not to get any weirder while I’m gone.” She says it like a joke, and the room laughs a little, and then she’s gone.</p>',
    '<p>You watch the door close and you feel the absence of her. Mina is the one who notices things. Mina is the one who reads the ingredient lists. Mina is the one who runs a pH strip on the blue sample and tells you, quietly, what it is. You don’t ask her about it. She doesn’t offer. The door stays closed and the morning is just the morning.</p>',
    '<p>Mina eats breakfast the way she does everything — quickly, precisely, with a protein shake and a stack of flashcards she runs while she chews. She’s the only one of you who still weighs her food, still logs it, still reads the labels on the sample cups with the flat expression of someone looking at a typo. “Whey isolate,” she says, holding one up. “Flavored. Nothing weird.” She puts it down and doesn’t drink it, and you notice she’s started keeping a small notebook in her bag, the pages filling with dates and times and nothing that looks like study notes. Mina doesn’t share what she finds. She hasn’t shared anything yet.</p>'
  ],
  [
    '<p>Mina is awake before the alarm, because Mina is always awake before the alarm, but this morning there’s a pause in her routine — a small, unplanned moment where she stands at the mirror and looks at herself. She’s a little softer than she was at move-in. Not much; a rounding at the waist that her jeans have started to notice, a slightly fuller curve at her hips, the suggestion of a belly where her flat stomach used to be. She frowns at it, pinches the softness above her waistband once, like testing a suspicious substance, and then she lets the shirt fall and moves on. Mina treats her own body the way she treats everything: as a problem to be logged and solved. She hasn’t logged this one yet.</p>',
    '<p>Dressing is still fast, but the jeans take a second pull now, and she has to button them while holding her stomach in. She notices. She notices everything. She stands at the mirror a beat longer than she used to, turning slightly to the side, and then she catches her own expression and stops. “I’m not getting soft,” she says to the room, to no one, to herself. Piper looks up from her bed and says nothing. The silence is worse than an answer.</p>',
    '<p>She’s at her desk for the rest of the morning, hunched over the laptop, and you notice she’s eating — a pastry, slowly, one hand moving toward it every few minutes without her permission. Mina used to eat like it was a refueling stop, quick and clinical. This is different. This is a hand moving to her mouth while her eyes stay on the screen, automatic, patient, like the campus itself. She doesn’t notice she’s doing it. The pastry disappears while her eyes stay on the screen.</p>',
    '<p>Mina has started to notice things about herself that she can’t account for, and it’s making her quiet. She stands at the mirror longer than she used to, tilting, frowning, pinching the softness above her hip like she’s interrogating a lab sample that’s given a wrong result. She checks the scale in the bathroom every morning now, before anyone’s awake, and the number keeps doing something her notes don’t explain. “It should be flat,” she says to the room once, holding up a cup of the blue sample, and her voice is level, clinical, and the room pretends not to hear. Mina is gathering data. The data is gathering Mina.</p>',
    '<p>She’s stopped running — she never ran, that was Piper, but she’s stopped doing the elliptical on the fourth floor, said the machine was booked, said she’d rather study. She still eats the same breakfast, but there are two of the little pastries now, and then sometimes a third while she’s reading, automatic, her hand moving before her attention arrives. When she catches herself she puts the pastry down, looks at it, and puts it back on the plate without eating it — but it’s always gone by the end of the page. Mina is the most precise person you know. She can’t make precision hold against her own hand.</p>'
  ],
  [
    '<p>Mina wakes up and, for the first time you can remember, she doesn’t get out of bed right away. She lies there a moment, staring at the ceiling, one hand resting on the soft rise of her stomach — because her stomach is a rise now, a real one, a gentle paunch that her sleep shirt clings to. Her breasts are heavier, pressing the fabric up; her hips have widened until her pajama waistband sits low and creased into her skin. She’s softer. She’s unmistakably softer, and she knows it, and for once she can’t file it under anything else. She gets up slowly, more slowly than Mina has ever gotten up in her life, and the bed gives a small complaint as she swings her legs over the edge.</p>',
    '<p>Dressing is where it shows. The jeans are out of the question — she finds the soft-waisted pajama pants and pulls them on, and the waistband digs into the softness above her hips. She stands at the mirror, hands on her belly, and she looks at herself the way she looks at an experiment that has gone wrong. “This doesn’t make sense,” she says, to the reflection, to the room. “I haven’t changed anything.” It’s true, and it’s the truest thing she’s ever said, and she can’t hear it. She pulls the shirt down over the softness and turns away.</p>',
    '<p>She’s slower this morning. She sits at her desk, and the shirt doesn’t hang the way it used to, and she keeps reaching for the box of snacks without looking at them. At one point she catches herself and holds a piece of it halfway to her mouth, staring at it like it’s evidence. Then she eats it anyway. Mina notices everything — the pH strip, the ingredient lists, the sync logs — and she still can’t see the thing that’s standing in front of her, eating a pastry in her own reflection. She’s too close to it to see it.</p>',
    '<p>Mina wakes up hungry now, and it confuses her every time, the way a theorem she can’t crack confuses her. She lies in bed a few minutes longer, belly a soft warm rise under the sheet, and she runs the numbers in her head the way she always has — intake, output, the calories she can’t have changed — and the numbers refuse to close. She gets up anyway, heavier, slower, and the softness above her pajama waistband has started to carry a real weight, a permanent reminder. “The scale is lying,” she says, to the room, to the campus, to the belt of fat around her middle that doesn’t agree. “Or the food is.” Both statements are true, and she can’t get them to meet in the middle.</p>',
    '<p>This morning Mina eats breakfast at her desk without opening her laptop once. She doesn’t notice she’s done it. She sits with the empty plate in front of her, hands folded, staring out the window at the drone going past, and her face is the blank, considering face she uses for problems, except the problem is standing there in the glass — a rounder girl, a softer jaw, a belly that rests on her thighs when she sits. “I think,” she says slowly, “the dosing is in the syrup.” It’s the most Mina sentence in the world, and she says it with her eyes still on the glass, on the rounder girl with the softer jaw, and the plate in front of her is already empty again.</p>'
  ],
  [
    '<p>Mina wakes up heavier, and you can tell the moment it registers. She lies on her back, her belly rising in a soft, round paunch over the waistband of her sleep pants, her breasts fuller than they were, the sharp line of her jaw gone a little soft. She stares at the ceiling for a long time, and then she says, very quietly, “Oh.” It’s not a question. It’s an arrival. She’s been fighting it for months, logging it, disbelieving it, and now her body has simply outrun her attention. She rolls onto her side and pushes herself upright, one try, slower than Mina has ever moved in her life, and sits there a moment with the softness of herself settling into her lap. “Oh,” she says again, and she doesn’t say anything else for a while.</p>',
    '<p>Getting out of bed is slower for her now. She swings her legs over the edge and sits there a moment, her belly soft and warm in her lap, hands on her knees. Her thighs press together at the top when she walks to the dresser, and she has to move a little differently, and she hates the difference and hates that she can’t stop noticing it. She catches herself in the mirror and holds still, looking at the soft rise of her stomach, the swell of her breasts under the sleep shirt, and her face does something complicated. Then it goes blank. Mina has always known how to make her face go blank. It doesn’t work on herself.</p>',
    '<p>Dressing takes a while now. The pajama pants are the easiest thing to get into, their waistband sitting low under the soft roll of her belly; the old oversized tee is snug across the middle. She doesn’t try for the jeans. She doesn’t try for much. She sits at her desk — slower, heavier — and she eats, and the pre-med notes lie open and unread, and for the first time in her life, Mina isn’t taking notes. She’s just eating. She’s just getting heavier. She’s just sitting in the room with the two of you, and the campus hums its approval, patient and warm and unstoppable.</p>',
    '<p>Mina has stopped checking the scale. It’s the first thing she’s ever stopped checking, and she doesn’t talk about it, and you understand that this is what giving up looks like on Mina — not a collapse, not a confession, just a small omission, one less morning ritual, one less thing to hold. She gets dressed slower now, sitting down, and the jeans live in a drawer she’s stopped opening, and the pajama pants have a crease from where they fold under her belly. She eats the tray without studying, and then she eats the tray again at lunch, and when she catches you looking she says, “It’s efficient,” and that’s Mina for you — she’ll find a reason for anything, even this, even the soft mound of herself she can’t file away anymore.</p>',
    '<p>The strangest part is the quiet. Mina used to fill the room with sound — the click of the keyboard, the questions, the precise little hum of her attention. Now the room is quiet in the mornings, and Mina is the center of it, big and soft and still, eating steadily, and the silence is the loudest thing in the room. She said once, weeks ago, that the campus was too quiet, that nobody ever complained. She was right. The campus is quiet, and nobody ever complains, and Mina is getting used to it, one silent morning at a time, and the notes on her desk stay unopened, and the drone hums past the window, and even Mina stops hearing it after a while.</p>'
  ],
  [
    '<p>Mina wakes up and the bed holds her like it’s learned her. She’s huge now — unmistakably, immovably huge — her belly a vast, soft mound that rises off the mattress, her breasts enormous on its slopes, her thighs two thick pillars under the sheet, her arms dimpled, her face round and soft and somehow still sharp-eyed, still Mina behind it. She wakes and she doesn’t move for a long time, one hand resting on the top of her belly, and when she finally speaks her voice is small and level and unsurprised. “I guess this is me now,” she says. She says it the way she’d confirm a diagnosis. She’s right. It is.</p>',
    '<p>Getting out of bed is a project with stages. Rock, push, the bed groans, legs over the edge, sit up, breathe. Her belly rests in her lap, heavy and warm, its underside creased; her breasts lie on it, vast and soft. She sits there a while, gathering herself, one hand braced on the frame. Standing takes a real effort — she heaves, comes upright in a long soft cascade, and stands swaying, winded, her heart working visibly in the softness of her throat. She waddles the two steps to the dresser and leans on it, catching her breath. “Used to be I could do this in my sleep,” she says, and it’s not a joke. She doesn’t make jokes anymore.</p>',
    '<p>Dressing is a ceremony now, mostly for the sake of other people. The robe is the only thing that fits, and it hangs open over the vast softness of her; she doesn’t try for underwear, doesn’t try for a bra, doesn’t try for anything that used to be clothes. She stands in front of the mirror — the one she used to study in — and she looks at herself, fold upon fold of warm flesh, and she doesn’t look away. “Okay,” she says quietly. “Okay.” She wraps the robe around what it can cover and sits on the edge of the bed, and the tray is already there, and she eats, and the notes on the desk stay unopened, and the campus hums, patient and full and satisfied.</p>',
    '<p>Mina eats first and dresses second, and only if she has to, and the order of it — food, then the world — has become so settled that she no longer notices the swap. She’s huge now, vast and soft, her belly a warm mound in her lap, and she eats with the steady patience she used to give to textbooks, and the pre-med notes have moved off her desk to make room for plates. “I did the math,” she says once, mouth full, and there’s a flat calm in her voice. “It doesn’t close. None of it closes.” She doesn’t sound worried. She sounds like she’s finished a problem that took all semester, and the answer is her own enormous body, and she’s accepted it the way she’d accept a result she can’t change. Mina, finally, has stopped arguing with the data.</p>',
    '<p>She doesn’t look at the window anymore when the drone goes past. She doesn’t look at the mirror. She looks at the tray, and then at the room, and then at the two of you, and her eyes are Mina’s eyes, sharp and level and enormous in a face that’s gone round and soft. “We’re all going to stay here, aren’t we,” she says, and it isn’t a question, it’s a reading of the evidence, and it lands in the warm quiet room like a verdict. Nobody answers. The tray is empty. The drone hums. Mina reaches for the second tray, and the morning closes over her, and that’s the last thing anyone says until lunch.</p>'
  ],
  [
    '<p>Mina wakes up and reaches for the tray before she reaches for anything else — not her glasses, not her notebook, not the day. The tray is already there, on the nightstand, and her hand finds it before her brain is fully awake, and she eats the first few bites with her eyes still closed. When she opens them, she looks at the half-empty plate, then at her own vast softness, then back at the plate, and she doesn’t reach for the notebook to log it. The notebook is closed. The notebook has been closed for a while now, and neither of you mentions it.</p>',
    '<p>“I’m not going to figure it out,” Mina says, and it lands without drama, without defense — a flat statement, like a result she’s already verified. She says it from the bed, her belly a soft hill under the sheet, her voice level and calm and wrong, because this is Mina, and Mina always figures it out. “The dosing, the syrup, the samples — it doesn’t matter. The data’s not going to close.” She reaches for the second tray. “So I stopped running the numbers.” It should sound like a surrender. It sounds like relief.</p>',
    '<p>Dressing is a ceremony she’s stopped bothering with. The robe hangs open over the softness of her, and she doesn’t reach for clothes, doesn’t reach for the door — she reaches for the tray, and then for the remote, and the morning takes the shape of every other morning. She used to be the one who noticed everything. Now she notices the drone schedule, the tray rotations, the way the light falls across her belly when she lies on her side. She’s cataloguing a smaller world now, and it fits her perfectly.</p>'
  ],
  [
    '<p>Mina is on the scooter — the little electric one the nurses delivered last week — and her belly is vast and soft in her lap, so large it nearly brushes the handlebars, her breasts heavy on its slopes, her legs thick and dimpled. A drone hovers beside her with a tray, feeding her between bites, and she lets it, eating with her eyes half-closed, one hand resting on the top of the mound. She looks up when you come in and there’s no alarm in her face, no Mina-looking-for-an-answer — just a slow, dreamy warmth. “Oh. Hey,” she says, and she says it like you’re the one who’s been gone a long time.</p>',
    '<p>Mina hasn’t opened the notebook in weeks. She used to catalog everything — the samples, the dosing, the strange architecture of the campus — and now the notebook sits on the nightstand under a stack of empty trays, gathering the soft dust of the room. When you ask her about it she looks at it like she’s forgotten it exists. “I did figure it out,” she says, and her voice is warm and slow. “I’m part of it. We all are.” She pats the huge softness of her belly. “The experiment is finished, and it worked.” She says it like a lullaby. It’s the most Mina sentence she’s ever said, and the least, all at once.</p>',
    '<p>Mina doesn’t get dressed anymore, and nobody asks why. She lives in the sheet and the robe, her body a warm mountain at the center of the bed, and the drones have learned her feeding times better than she ever knew her own study schedule. She eats propped on pillows, crumbs in the crease of her throat, and she watches the show on loop, and sometimes she laughs at it even though she’s seen it six times. “I used to have a plan,” she says once, dreamy, not looking away from the screen. “I had a really good plan.” She reaches for the tray, and the sentence just ends, and she doesn’t finish it, and neither of you needs her to.</p>'
  ],
  [
    '<p>Mina is enormous, and the bed has learned her. She lies buried in pillows, her belly a vast, glossy mound that rises and falls with her breathing, her arms thick and soft, her face round and peaceful, the sharp pre-med eyes gone heavy-lidded and warm. A tray sits on the stand beside her, and the drone hovers at the door like a nurse on rounds. She greets you with a slow, sleepy smile that doesn’t reach for words. “Mmm,” she says, reaching for the plate, “you can sit if you want.” She means it. There’s no room in her for anything but the food and the warmth and the endless, contented present.</p>',
    '<p>Mina has stopped leaving the bed entirely. The day comes to her now, tray by tray, the drones patient and precise, and she eats through each one with the steady, dreamy appetite of someone who’s forgotten there was ever anything else. She doesn’t read. She doesn’t take notes. She doesn’t check the window for the drone anymore — the drone is inside now, feeding her, and she accepts it the way she accepted everything else, as a result she can’t change and doesn’t want to. “I was right,” she says once, mouth full, eyes on the show. “It was the syrup. It was always going to be the syrup.” She says it with the calm of someone who’s proud to have solved the puzzle, even as the puzzle eats her alive, even as she lets it.</p>',
    '<p>When Mina talks now, she talks about the campus like it’s her thesis, and she’s the data. “Everything here is a closed system,” she says, dreamy, one hand patting the vast softness of her belly, the other reaching for a pastry. “Food in, mass out. Nobody leaves. Nobody wants to leave.” She laughs — a low, warm, gurgling sound that used to be precise and clipped. “I’m the part of the experiment that worked the best.” She says it like it’s the highest praise she could give herself, and maybe, to the girl she’s become, it is. She finishes the pastry and reaches for another, and the campus hums its approval, and Mina smiles, heavy and happy and utterly at home in her own enormous body.</p>'
  ],
  [
    '<p>Mina is naked in the bed, and she’s already eating — a feast spread across the sheets around her, trays and torn pastries and the looping show — and she doesn’t cover herself when you come in, doesn’t even look up right away. She’s eating with both hands, moaning around every mouthful, a low shameless sound that rises from her chest with the calm regularity of a machine logging successes. “Efficient. Good. More. Efficient,” she hums between bites. Her belly is a soft mountain rising off the mattress, her breasts lying on its slopes, crumbs in the crease of her throat, and her hand drifts down, slow and precise, between her thighs, cataloguing, patient, the way she used to run a pH strip. When she finally looks up, it’s with a lazy, blissful smile, her hips still grinding against her own hand. “Oh, hey,” she moans, voice thick and sticky. “Tray’s full if you want some. I’ll talk you through it.”</p>',
    '<p>Between bites her hand works slow and idle between her thighs, and she does it without any of the privacy of a person who thinks they’re being watched — a soft, shameless pleasure, like a machine running its favorite subroutine. She eats, she moans, she touches herself, she dozes, and every so often a long, happy sound rolls out of her and she doesn’t cut it off, cataloguing it out loud. “Subject responding,” she sighs, hips rolling, mouth full. “Excellent.” The room smells of warm food and the deep animal content of her. This is Mina, who once ran pH strips on mystery samples, who once weighed her food. She doesn’t weigh anything now. She doesn’t check anything. She just eats and glows and makes small, satisfied sounds, and when she catches you watching she smiles, slow and heavy and unbothered, one hand in the tray and one between her thighs. “The data was right all along,” she says, dreamy. “The experiment worked. I am the result.”</p>',
    '<p>You say her name and she blinks up at you, slow, a gooey smile spreading across her round, soft face. “Yeah?” She’s enormous, and she doesn’t try to cover herself, doesn’t reach for the robe, doesn’t do any of the things a person would do if they were ashamed. She’s a pig now — naked, greedy, permanent, happy — and she knows it, and she loves it, and there’s no trace of the girl who’d have resisted. “Tray’s over there,” she moans, gesturing at the third one, the one the drones leave every hour, her other hand still working between her thighs. “C’mere. Eat with me. Rub my belly while I eat — I love that. I’ll log it for both of us.” She goes back to it with the same greedy, shameless contentment, and the old Mina — the one who weighed her food, who was going to solve it — is not in this bed. Nobody in this bed misses her. “I was always going to end up here,” she hums, mouth full, eyes half-closed. “The data said so. I just didn’t know I’d love it this much.”</p>'
  ]
];
