'use strict';

const DINE_PIPER = [
  '<p>Across the table, Piper is mid-conversation about her training plan, talking a mile a minute around mouthfuls of salad and chicken. She eats like she runs — fast, economical, everything moving. She hasn’t touched the dessert tray, hasn’t looked at the vending machines, hasn’t even slowed down. She’s still the girl who ran three miles before breakfast, and you watch her for a second before the conversation pulls you back in.</p>',
  '<p>Piper eats a little more than she used to, and she does it with the same bright energy, laughing between bites, reaching for the bread basket as she talks. Her waist is a little rounder over the top of her leggings, her face a little softer, and she’s still the loudest, warmest person in the room. “Freshman fifteen,” she says, waving a hand, and she says it so easily that you almost believe her, and then she reaches for the second basket without pausing.</p>',
  '<p>Piper is on her second tray, talking with her mouth full, her belly pressing soft against the table edge. She’s softer now — rounder at the middle, fuller in the face — and she eats with a steady, cheerful appetite that doesn’t pause for breath. “Coach says rest is training too,” she says, and she laughs, and it’s the same laugh, just carrying more weight. She doesn’t mention the track anymore. She doesn’t mention a lot. She just eats, and smiles, and the tray empties, and you both pretend not to notice.</p>',
  '<p>Piper comes back from the line with a tray stacked higher than it used to be and settles onto the bench beside you, her belly pressing soft and round against the table edge. She’s heavy now, no question — rounder through the middle, softer in the face, her shirt pulled snug across her chest — but she sits the way she always sat, easy and warm, one hand working through the food while she talks. “This is the good part of the day,” she says, around a mouthful, and she means it, and she reaches for the bread basket without pausing, and it’s hard to remember the girl who ran. Neither of you says that.</p>',
  '<p>Piper takes her tray — and then goes back for a second one before she’s even sat down — and lowers herself onto the bench, her belly pressing soft and heavy against the table’s edge. She eats steadily, methodically, her head down, and there’s no conversation to keep up with her food the way there used to be. The tray empties and she starts on the bread basket without pausing. “Might not make it to the quad tonight,” she says, around a mouthful, and she says it like a good thing.</p>',
  '<p>Piper is too big for the bench now — she sits at the end table where the chairs have arms, and she doesn’t get up between courses. A drone brings the second tray to her, and the third, and she waves her hand at the vending machine and the blue cup comes to her too. “The app says I need it,” she says, and she says it like a blessing. “The app’s never wrong.” She is huge, and she is happy, and she has stopped pretending to be the girl who ran.</p>',
  '<p>Piper is enormous, and she doesn’t hide it. She’s propped on the scooter, her belly vast before her, and the drone feeds her between long, contented swallows, and she lets out a low burp without even looking up from her phone. “That’s better,” she says, and it comes out warm and satisfied, and she smiles at you, the same bright Piper smile, just wider, just softer. She is so happy. That’s the worst part. She is so, so happy, and the tray is already coming back, and she opens her mouth without being asked.</p>',
  '<p>Piper is enormous, and she still wheels herself down for every meal — though it takes her most of the walk, the scooter humming through a lane the commons has widened just for her. She idles at the end table, vast and soft, and the drone brings the tray and then the next one, and she eats without ceremony, one hand on the handlebars, a low burp rolling out of her every few minutes. She doesn’t talk about the track anymore. She doesn’t talk about much. But she’s still here — the heaviest girl in the room and the last one who still shows up for it.</p>',
  '<p>Piper doesn’t come to the commons anymore — she can’t, not really; the scooter can’t manage the doors and the tables are too close together. A drone brings her tray to the doorway of the room and comes back for it empty, and the sound that carries down the hall now isn’t just the drone — it’s her, eating and moaning, greedy and shameless, a low animal pleasure that the whole floor has learned to live around. Sometimes the door is ajar and you catch her: naked in the wreckage of the feast, one hand in the tray and one hand between her thighs, her hips rolling, a long wet moan rising between mouthfuls. There’s an empty place at the table where she used to sit, and nobody sits in it, and nobody mentions it. Whatever Piper is doing up there, the room knows, and the campus knows, and the knowing is as warm and accepted as everything else here.</p>'
];


