'use strict';

function piperZolaMorn(pt){
  if (pt <= 2){
    return '<p>Piper sleeps in now — she never used to — and when she wakes she doesn’t stretch, doesn’t reach for her shoes. She lies there a moment, blinking at the ceiling, and then she says, softly, dreamily: “Zola says rest is for runners.” She says it like a mantra she’s learning to pray. She gets dressed slow, and her hand finds the box of pastries before her feet touch the floor. “She said to eat,” Piper says, and she says it like it’s the most natural instruction in the world, like Zola is the coach and the sun and the app all at once. “She said I’d be happier. I am. I’m so happy.”</p>' +
      '<p>Piper is on her phone before breakfast — texting. She never texts anyone. “Zola,” she says, when you ask, and her smile goes slow and gooey, like the word itself tastes like honey cake. “She wants me at the commons by nine. She’s got a new tray for me.” She tucks her phone away and hums, dreamy, and you watch her leave with a skip in her step that has nothing to do with running.</p>';
  }
  if (pt <= 5){
    return '<p>Piper is on her bed, propped against the pillows, a tray already open in her lap before she’s finished waking. She eats without ceremony, moaning softly between bites, and when she notices you she grins, crumbs on her chin, eyes soft and far away. “Zola fed me last night,” she says, dreamy. “She says I’m doing so well.” She pats the soft rise of her belly, possessive, proud. “She says I’m getting exactly where she wants me.” She says it like it’s a compliment she’s been waiting her whole life to hear, and maybe it is.</p>' +
      '<p>Piper doesn’t run anymore. It isn’t a decision — it’s just that the morning finds her at Zola’s table, a tray in front of her and Zola’s hand on her back, feeding her like she’s something precious. She comes back to the room smelling like glaze and perfume, full and slow and happy, and she talks about Zola the way she used to talk about training splits — with reverence, with numbers, with a kind of devotion that makes you feel like you’re watching a conversion. “She says I’m hers,” Piper says, dreamy. “She says I’m the best thing that ever sat at her table.” She laughs, low and warm. “I believe her. I believe everything she says.”</p>';
  }
  return '<p>Piper doesn’t get up for breakfast anymore. A drone brings her tray — and then Zola’s, because Zola visits her now, the enormous woman wheeled into the room on her scooter, feeding Piper by hand, cooing over every bite. “She’s mine,” Zola says, loud enough for you to hear, stroking Piper’s hair. “Aren’t you, sweet girl?” And Piper moans around the mouthful, eyes half-closed, nodding, her whole vast body humming with contentment. “Yours,” she says, voice thick. “All yours.”</p>' +
      '<p>Piper is enormous now, and she is Zola’s, and the two are not separate facts anymore. She lies in her bed, buried in pillows and trays, and when she talks it is in Zola’s cadence, Zola’s warmth, Zola’s certainty. “The table’s the only place worth being,” she says, dreamy, one hand in the tray and one between her thighs. “Mama Zola said so. She’s always right. She’s never been wrong about me.” She moans, soft and happy, and the drone hums in the hall, and somewhere in the commons you can hear the low steady hum of Zola eating, patient, waiting for her girl.</p>';
}

function piperCourtingMorn(left, pt){
  if (left <= 3){
    return '<p>Piper is on her bed, staring at her phone, and she doesn’t notice you for a long moment — then she looks up, and her face is flushed and dreamy, and she puts the phone down face-first, guilty and pleased. “Zola’s been talking to me,” she says, and the name comes out soft, like she’s tasting it. “She says she has a place for me at her table. She says I’d love it.” She picks the phone back up, and her thumb is already scrolling. “She keeps asking about me. About how I eat. About what I want.” She bites her lip. “Nobody’s ever asked me that before.”</p>';
  }
  if (pt <= 4){
    return '<p>Piper is up early — for once — dressed and bright, and she’s already heading for the door before breakfast. “Commons,” she says, and she says it the way she used to say track, with the same bright hunger. “Zola’s saving me a seat.” She grins, and it’s the old grin, just warmer, just softer. “She says I should come sit with her. She says I’m exactly her type.” She’s gone before you can ask what that means, and the room feels emptier without her.</p>';
  }
  return '<p>Piper is on her bed, talking to her phone, and the name on her lips is one you’ve heard from her more and more: “Zola.” She hangs up and turns to you, bright and a little breathless. “She wants to meet me,” she says. “The big girl at the commons table. She says she’s been watching me eat and she thinks I’ve got potential.” She laughs, the old bright laugh, but there’s a tremor in it — curiosity, hunger, something new. “I don’t know what she wants, but she’s… interesting. She makes me feel like I’m worth feeding.”</p>';
}

const PIPER_MORN = [
  [
    '<p>Piper is awake before any of you, the way she’s always awake. She’s sitting cross-legged on her bed in running shorts and a sports bra, mid-stretch, and she looks like the cover of a brochure: thin, long-limbed, the fine muscle of her stomach a neat ladder under the skin, her breasts small and high, her hips narrow. Her ponytail is sharp as a blade. She catches you watching and grins. “Sleeping in, huh? I’m already three miles in.” She rolls her shoulders, cracks her neck, and hops off the bed in one clean motion, landing with her weight perfectly under her. Nothing about her wobbles. Nothing about her ever wobbles.</p>',
    '<p>Getting dressed takes her no time at all. The running tights go on in a single pull, the tank over her head, and she laces her shoes without looking down. There’s a compactness to her, a density — you can see every line of her, the definition in her thighs, the flat of her stomach as she bends to tie her laces. She stands, bounces twice, and she is ready. “Protein shake?” she says to the room, already moving, and her energy fills the space like it’s been waiting to. Mina mumbles something from her desk. Piper laughs and is gone before anyone can answer.</p>',
    '<p>You watch her leave and you feel the shape of the day settle around you. Piper is the only fixed point in this room, the one thing that hasn’t started to change. She drinks her shake on the way to the gym, she runs before class, she eats the salad bar like it’s a chore. She’s still light. She’s still fast. You watch her go and the day settles around you, ordinary and bright, and the room is quieter with her out of it.</p>'
  ],
  [
    '<p>Piper runs at dawn, every day, and she does it because she loves it — the cold air, the empty track, the way her body does exactly what she asks of it. She comes back pink-cheeked and sweating and eats a banana standing in the kitchenette, still bouncing on the balls of her feet. “You should come,” she says to you, mouth full, the same invitation she’s made every morning this week. “It’s the best part of the day.” You say maybe. Piper doesn’t push. Piper never pushes. She just keeps running, and eating, and being the fixed bright point of the room. You say maybe, and she grins, and the morning is warm and ordinary, and that’s the last thing either of you says about it.</p>',
    '<p>Piper wakes up stretched along her bed like a long, contented cat, one arm above her head. She’s a little softer than she was at move-in — not much, just a rounding at the waist, a gentler curve at her hip where the running tights used to sit sharp. Her breasts fill her sports bra a shade more fully, and her belly, when she stretches, is a smooth, soft rise instead of a flat plane. She yawns, cracks her neck, and sits up, and there’s a small breath of effort in it that wasn’t there in August. “Could have run,” she says to no one, “but the bed was winning.” She says it lightly. She doesn’t notice she said it.</p>',
    '<p>Dressing is still fast, but it’s not instant. The tights pull up over a little more hip than before, and she has to wiggle to settle them. The tank top, the old one, sits snugger across her chest, and she looks down at herself once, frowning slightly, then decides not to look again. She laces her shoes and stands, and the bounce she gives is a half-bounce — a little more weight, a little less lift. “I’ll catch you guys later,” she says, and there’s a pause where she used to say track, or trail, or tempo. She doesn’t say any of them. She just goes, a little slower out the door than she used to be.</p>'
  ],
  [
    '<p>You watch her go and you think about the salad bar. You think about the protein shake. She’s still Piper — bright, fast, unstoppable — but there’s a softness creeping in at her edges, and you watch it the way you watch the light move across the floor, without being able to say when it started.</p>',
    '<p>Piper still runs, but the runs are getting shorter, and she’s stopped timing them. She says it’s the semester, the course load, the shorter days. She says it the way you’d say something you’ve decided to believe. This morning she sleeps in — actually sleeps in, a whole extra hour — and when she wakes she stretches and her belly rounds out over the waistband of her sleep shorts in a soft, unmistakable arc, and she looks at it for a second before she looks away. She gets dressed without the bounce. She eats an extra helping of toast at breakfast, and then another, and she says “carbs” like it’s a joke, like it’s a small rebellion, like it isn’t already the shape of a surrender she hasn’t named.</p>',
    '<p>You watch her in the mirror while she brushes her teeth — a long, lean girl, still, but softer at the edges, the way all of you are getting softer. She catches your eye and grins around the toothbrush, and there’s something lighter in her now than there used to be, a small settling. She used to be all edges, all forward motion. Now there’s a pause in her, a gentleness, a willingness to sit and stay a minute longer. “This place is weird,” she says, not looking at the mirror, and it’s the closest she’s come to saying anything true in weeks. “But the food’s good. The food’s always good.” She rinses, and the moment goes, and she’s bright Piper again — brighter, softer, one small degree slower than she was.</p>'
  ],
  [
    '<p>Piper wakes up slow, the way she does now. She’s on her back with her hands folded on her stomach — a stomach that is unmistakably not the one she moved in with. It’s a proper paunch now, round and soft, rising in a gentle hill under her t-shirt; her breasts are heavier, fuller, pressing the fabric up; her hips have widened until her sleep shorts sit low, half-buried under the roll of her belly. She blinks at the ceiling for a long moment before she moves, as if giving herself time to remember the shape she’s in. Then she sighs — a small, contented sound — and she reaches for the box of pastries on the nightstand before she even sits up.</p>',
    '<p>Getting out of bed is a two-part motion for her now. She pushes up onto her elbows, sits, lets the blood settle, and swings her legs over the edge. Her belly settles forward into her lap, heavy and warm, and she rests a hand on it without thinking, like it’s a pet she’s fond of. Standing takes a beat. Her thighs, thicker now, rub together at the top when she walks the three steps to the dresser, and her breasts swing heavy under her shirt. She catches herself in the mirror and holds her own gaze for a second, then turns away. She doesn’t frown. She doesn’t smile. She just turns away, which is somehow worse.</p>',
    '<p>Dressing is a negotiation. The tights are gone — they live in the bottom drawer under things she won’t admit don’t fit. She’s into sweatpants now, soft-waisted, and a big t-shirt that hangs off one shoulder. The bra takes longer: hook, adjust, re-hook, her arms working around a back that’s thicker than it used to be. She catches you looking and grins, a real grin, the old one. “Don’t start.” She pulls the shirt on, smooths it over her belly, and it doesn’t cover the roll at the waistband. She leaves it. She’s started leaving it.</p>'
  ],
  [
    '<p>“I’m not running today,” she says, and it lands so casually, so naturally, that neither of you acknowledges what it means. She says it the way you’d say you’re not going to the movies. The room is quiet for a second, and then she’s talking about the honey cake, and the moment is gone. Piper is softer, rounder, slower — and she says it so easily, so lightly, that it doesn’t sound like anything at all.</p>',
    '<p>Piper gets dressed sitting down now, and she doesn’t make a thing of it. She sits on the edge of her bed, legs apart to make room for the soft weight of her middle, and pulls on the sweatpants and the big shirt, and when the shirt rides up over the roll of her belly she smooths it down once, twice, and then leaves it. “Pastries,” she says, “are a food group,” and she laughs, and it’s a real laugh. It’s the strangest thing about this whole semester, the way the softer she gets, the happier she sounds. She used to need things — a goal, a distance, a time to beat. Now she wants toast, and company, and the warm middle of the morning, and she has all three, and she’s got no idea she’s been traded in for them.</p>',
    '<p>Piper wakes up slow, and for a minute she just lies there, one hand resting on the soft rise of her belly under the sheet. She’s heavier now — you can see it in the way the sheet rounds over her middle, in the fuller curve of her breasts, the rounder line of her jaw. She stretches, yawns, and pushes herself up onto her elbows, and there’s a small breath of effort in it that wasn’t there in August. “Morning,” she says, and her voice is warm and rough and easy, and she smiles like nothing’s changed, which is the least convincing thing you’ve ever heard.</p>',
    '<p>Sitting up is easy enough; it’s the standing that takes a second now. She swings her legs over the edge of the bed, and her belly settles soft and warm into her lap, and she rests a hand on it without thinking, like it’s just part of her now. She pushes up, a little heavier on her feet than she used to be, and pads the few steps to the dresser. “Used to be I’d be at the track by now,” she says, and she says it lightly, and for the first time it doesn’t land like a joke. It lands like a real loss, a real thing she’s given up without ever deciding to.</p>'
  ],
  [
    '<p>Dressing takes longer than it used to. The tights live in the bottom drawer now; she’s into soft-waisted sweatpants and a t-shirt that hangs loose over the curve of her belly. The bra hooks a shade tighter than it did at the start of the semester, and she adjusts it once, twice, then leaves it. She catches you looking and grins, the old grin. “Don’t start.” She smooths the shirt down over her middle, and it rides up at the hem when she moves, and she leaves it. She’s started leaving it.</p>',
    '<p>“There’s a tray by the door,” she says, and it comes out before she’s thought about it, and for a second she looks almost surprised at herself. Then she pulls it onto the bed and eats, sitting up against the headboard, and the morning becomes the same shape every other morning has become. Piper is heavy now, and round, and she doesn’t run anymore, and she tells herself it’s fine, and the worst part is how much she means it.</p>',
    '<p>Piper finishes the box of pastries while she’s getting ready, and then she reaches for the leftover honey cake while she’s looking for her shoes, and nobody counts any of it anymore, least of all her. She catches you watching and shrugs, crumbs on her chin, belly a soft round curve under her shirt. “I think I’m done fighting it,” she says, and there’s a strange peace in her voice, a quiet that wasn’t there in August. “Everything on this campus is getting softer. Everything. It’s easier to just… be soft too.” She says it like it’s a discovery, like she’s the first person to figure out the trick. You let her have it. The morning is warm, and the pastries are good, and it is easier to be soft too.</p>'
  ],
  [
    '<p>Piper wakes up like a landslide wakes up: slowly, massively, all of her coming into being at once. The bed is bowed to her shape — a deep hollow the exact size of her body — and when she rolls onto her back, her belly rises in a vast, glossy mound, its underside creased where it folds against her thighs; her breasts are huge, lying on the slopes of her stomach; her arms are thick, dimpled columns; her face is round and soft and somehow still bright, still Piper, the same eyes under the same long lashes. She wakes hungry — the first thing she does is reach for the tray on the nightstand before her feet have touched the floor. “Gotta fuel up,” she says, and there’s no run after it, and neither of you mentions that anymore.</p>',
    '<p>Getting out of bed is a project with stages. She rocks her weight, the bed groans, she gets her legs over the edge and sits up, her belly resting in her lap like a warm animal. She sits there a while, breathing, one hand on the top of the mound. Standing is a real push — she braces her hands on the bed frame, heaves, and comes upright in a long, soft cascade, her whole body swaying until it settles. Her heart works hard; you can see the pulse in the softness of her throat. She waddles the three steps to the dresser and leans on it, winded. “I used to do five miles before breakfast,” she says quietly, and it’s not a joke anymore, it’s a fact she’s telling like it happened to someone else. It did happen to someone else. That girl is gone.</p>',
    '<p>Dressing is mostly ceremony now. The robe is the only thing that goes around her, and even that doesn’t close — it hangs open over the vast softness of her, and she doesn’t try for underwear, doesn’t try for a bra, doesn’t try for pants. She stands in front of the mirror and looks at herself, and she’s enormous, and she holds her own gaze for a long time, and then she says, “Well,” and wraps the robe around what it can cover. She sits on the edge of the bed to catch her breath, and the tray is already open in her lap, and she eats with the steady, grateful efficiency of someone who’s stopped fighting it.</p>'
  ],
  [
    '<p>“I’m happy,” she says, around a mouthful, and it’s the truest thing she’s said in months. “I mean it. I’m actually happy.” And you believe her. That’s the awful part — you believe her, and she is, and the campus has won, and the quiet is so complete that you can hear the drone humming outside the window like it’s singing along. Piper is huge, and she eats in bed, and she’s happy, and the room has already reshaped itself around the three of you.</p>',
    '<p>Piper’s mornings have collapsed into a single, simple shape: wake, eat, rest, eat, maybe reach for a book she won’t read, eat again. She’s enormous, and she’s stopped pretending otherwise, and there’s a contentment to her that reads from across the room, warm and complete and more than a little terrible. “Don’t wake me for the quad,” she says once, mid-mouthful, and she says it with such ease, such settled gravity, that it lands like a rule, like a law the room has always had. The drone hums past the window. Piper eats. The morning holds its shape. It’s hard, sitting there, to remember she was ever the one who ran.</p>',
    '<p>Piper doesn’t do mornings anymore. She does trays — she surfaces when one arrives, eats through it lying on her back, the vast soft weight of her belly balanced like a hill under the plate, and sinks back down before the drones take the empty away. She’s too big for the routine of the day now; the day comes to her instead, in the form of the small army of trays that keep her exactly where she is. Once she would have been up and out the door by now. The door is a rumor to her now. The tray is the whole horizon.</p>'
  ],
  [
    '<p>Piper doesn’t wake up anymore — she surfaces, and she’s already eating. She’s naked, always naked now, the sheet pushed down to her thighs, her body a vast pale landscape in the morning light, her belly a soft mountain that shifts when she breathes. A tray waits on the bed beside her, and the drones have learned to bring it before she opens her eyes. She eats with her eyes half-closed, moaning around every mouthful, a low greedy sound rising from her chest, crumbs in the hollow of her throat. When she’s done she lets out a long, wet burp and doesn’t open her eyes, just sighs, dreamy, her hand sinking into the soft mass of her belly. “Mmm,” she hums. “Morning.”</p>',
    '<p>She doesn’t move for an hour, and then only to reach for the second tray. Between bites her hand drifts down, slow and unhurried, between her thighs, and she does it without any of the privacy of a person who thinks they’re being watched — a soft, idle pleasure, like stretching in the sun. She eats, she touches herself, she dozes, and every so often she moans, a low shameless sound that rolls out of her between swallows, her hips grinding lazily against her own hand, and the room smells of warm food and the deep, animal content of her. The drones keep the trays coming. Once you’d have felt something — embarrassment, worry, the urge to look away. Now it just seems like the most natural thing in the world, which is the most terrible thing about it.</p>',
    '<p>You say her name and she blinks up at you, slow, a gooey smile spreading across her round face. “Yeah?” She’s enormous — enormous in a way that has stopped being a state and become a way of life — and she doesn’t try to cover herself, doesn’t reach for the robe, doesn’t do any of the things a person would do if they were ashamed. Her hand is still between her thighs, the other one reaching for the tray, and she moans her welcome around a mouthful. “Tray’s over there if you want it,” she says, voice thick and dreamy. “C’mere. Eat with me. Rub my belly while I eat — I love that.” She goes back to it with the same greedy, shameless contentment, and the old Piper — the one who ran at dawn, the one who timed everything — is not in this bed. Nobody in this bed misses her.</p>'
  ]
];
