'use strict';

function dressMirrorGarments(base){
  const w = state.worn;
  if (w === 'active'){
    return base
      .split('the jeans sit a touch snugger').join('the shorts sit a touch snugger')
      .split('The jeans are snugger across the seat').join('The shorts are snugger across the seat')
      .split('You pull your shirt up over your head and stand there').join('You pull the sports bra up over your head and stand there')
      .split('You drop the shirt and run a hand down').join('You drop the sports bra and run a hand down')
      .split('You lift your shirt and look at your bare stomach').join('Your stomach is bare between the sports bra and the shorts, and you look at it')
      .split('You pull your shirt down over your belly and it rides up at the hem. You pull it down again. It rides up.').join('You tug the sports bra down over the softness above it, and it rides up. You pull it down again. It rides up.')
      .split('You lift your shirt and the whole of your stomach pours forward').join('Your stomach, bare between the sports bra and the shorts, pours forward')
      .split('You lift your shirt and the mound of your belly pours forward').join('Your belly, bare below the sports bra, pours forward');
  }
  if (w === 'robe'){
    return base
      .split('the jeans sit a touch snugger').join('the robe sits a touch snugger')
      .split('The jeans are snugger across the seat').join('The robe is snugger across the seat')
      .split('the waistband of your shorts').join('the belt of your robe')
      .split('the band of your shorts').join('the belt of your robe')
      .split('the hem of your shorts').join('the hem of the robe')
      .split('the shorts ride up').join('the robe ride up')
      .split('your shorts can’t quite cover').join('the robe can’t quite cover')
      .split('You pull your shirt up over your head and stand there').join('You let the robe fall open and stand there')
      .split('You drop the shirt and run a hand down').join('The robe hangs open as you run a hand down')
      .split('You lift your shirt and look at your bare stomach').join('You let the robe fall open and look at your bare stomach')
      .split('You pull your shirt down over your belly and it rides up at the hem. You pull it down again. It rides up.').join('You tug the robe closed over your belly and it falls open again. You pull it closed again. It falls open.')
      .split('You lift your shirt and the whole of your stomach pours forward').join('You let the robe fall open and the whole of your stomach pours forward')
      .split('You lift your shirt and the mound of your belly pours forward').join('You let the robe fall open and the mound of your belly pours forward');
  }
  const n = { rigid: 'jeans', soft: 'leggings', baggy: 'joggers' }[w];
  if (!n) return base;
  let out = base;
  if (n === 'jeans'){
    out = out
      .split('the waistband of your shorts').join('the waistband of your jeans')
      .split('the band of your shorts').join('the band of your jeans')
      .split('the hem of your shorts').join('the hem of your jeans')
      .split('the shorts ride up').join('the jeans ride up')
      .split('your shorts can’t quite cover').join('your jeans can’t quite cover');
  } else {
    out = out
      .split('the jeans sit a touch snugger').join('the ' + n + ' sit a touch snugger')
      .split('The jeans are snugger across the seat').join('The ' + n + ' are snugger across the seat')
      .split('the waistband of your shorts').join('the waistband of your ' + n)
      .split('the band of your shorts').join('the band of your ' + n)
      .split('the hem of your shorts').join('the hem of your ' + n)
      .split('the shorts ride up').join('the ' + n + ' ride up')
      .split('your shorts can’t quite cover').join('your ' + n + ' can’t quite cover');
  }
  const t = { soft: 'tee', baggy: 'hoodie' }[w];
  if (t){
    out = out
      .split('your shirt').join('your ' + t)
      .split('the shirt').join('the ' + t);
  }
  return out;
}

const MIRROR_NAKED = '<p>You don’t stand at the mirror anymore — you’re arranged in front of it, naked, and you’ve stopped noticing the arrangement the way you’ve stopped noticing most of the things that have become true. There is nothing between the glass and the vast soft mountain of you. No robe. No sheet. No apology. The whole pale expanse is there to be seen — breast and belly and hip folded together into one immense warm landscape, heaviest at the bottom, in the wide spread of your haunches and the canyon where your thighs press together. You touch it with a plump hand and feel the deep creases, the tender damp warmth where skin folds against skin for hours at a time, the slow full pulse of you at the center of all of it.</p>' +
  '<p>You catch your own face in the glass — small and calm and round, sunk into the padding, a settled, well-fed stillness that the scholarship girl left behind weeks ago. Your appetite hums behind it, patient and enormous, a second heart that never sleeps. The band hums on your wrist. The tray waits on the little table. The drone circles the roofline, satisfied. You look at the naked enormity of yourself the way you look at the room now — as the whole of the world, arranged exactly around you — and you don’t reach for anything, because there’s nothing left to reach for. You are naked, and enormous, and fed, and still, and that is all there is to be.</p>';

function mirrorText(){
  const texts = [
    '<p>You catch your reflection and stop. The girl in the glass is the one from the scholarship photo — average height, average frame, a waist that curves in cleanly, hips that are modest and easy, breasts small and high that barely move when you turn. Your belly is flat, a smooth pale field between your ribs and your hips, and when you press a hand to it you feel the neat architecture beneath — the ladder of your ribs, the firm wall of muscle, the shallow bowl of your navel. Your thighs sit apart when you stand with your feet together, a clean line of daylight between them. Your arms are light. Your wrists are thin enough that a watch would slide. Nothing strains. Nothing spills. Nothing waits for you. You are ordinary, in the grey light, in the only way you have ever known how to be.</p>' +
    '<p>You turn sideways and hold still, the way you used to in fitting rooms, checking for any hint of something you would rather not see. There is none. The flat line of your stomach meets the flat line of your hips, and the only softness on you is the harmless give of a thigh you can pinch without any of it staying. You pull your shirt up over your head and stand there, belly bare, breasts bare in the cool air, nipples tightening against it, and you are, in this grey light, exactly the girl you were in August. You hold that for a moment, and then the warmth of the room closes around you and the moment lets you go.</p>' +
    '<p>You drop the shirt and run a hand down your whole uncomplicated front — collarbone, ribs, the flat of your belly, the sharp notch of your hips. You could wear anything. You could run anywhere. You could stand here all day and none of it would cost you a breath. That is the thing about it: not the flatness, exactly, but the effortlessness — the way your body is a given, a quiet instrument that does what you ask without you ever having to think about it. You turn away from the glass and the girl in it turns away with you, and you leave the bathroom ordinary and easy and unbothered, and the morning is waiting for you.</p>' +
    '<p>You lean close to the glass and look at yourself the way someone who loves you would — kindly, honestly, without the daily cruelty of hurry. Your face is smooth and young, your collarbones a clean line, your shoulders straight. There is a whole unspent life in that face, a girl who still thinks hunger is a thing you answer with a salad, who still believes the body is a project you can win. The bathroom is warm with steam that hasn’t faded from the last shower, and your reflection breathes, and you are so small, so light, so entirely the girl who arrived here. You stand there a little longer than you mean to, and then you step back from the glass and reach for the door.</p>',
    '<p>The girl in the glass is only slightly different, and that is what keeps you looking. Your hips have begun to pad out, a softness at the sides that wasn’t there at move-in, and the jeans sit a touch snugger over the round of your ass. Your belly is still flat, mostly — a faint softness over the muscle — and your breasts are heavier by a degree. Your thighs press together at the top now when you stand, a soft damp warmth at the seam of your legs. None of it is dramatic. None of it is a stranger. It is you, but at a slightly larger size, like a photograph that has been cropped a little too generously at the edges.</p>' +
    '<p>You turn sideways and study the new line of yourself. The roundness is small but it is there — a gentle curve behind you, a matching softness at your sides where the waist used to cut in clean. You lift your shirt and look at your bare stomach — still flat enough that the ladder of your ribs shows faintly, but already wearing a faint softness over the muscle. You pinch the skin of your hip and it gives, slowly, and settles back. You could pass this off as the end of summer. You could call it water weight, or the welcome meals, or the week you stopped running. You tell yourself that and you almost believe it, which is the part you don’t want to look at.</p>' +
    '<p>You run your hands over the small new softness of your hips, over the slight heaviness of your breasts, feeling the difference the way you’d feel a new seam in a favorite shirt. The jeans are snugger across the seat; when you look over your shoulder you can see the roundness of your ass filling them out, the crease at the top of each thigh beginning to hold. Your navel has grown a little deeper, a little shadowed, tucked behind the gentle rise. You are not the same girl who arrived. You are not yet someone different. You are standing in the grey space between them, one foot still in the scholarship photo, and the mirror holds you there, patient, while you decide what to believe about what you see.</p>' +
    '<p>You catch your own eyes in the glass and hold them. The girl looking back is a little rounder at the hips, a little softer, a little slower in the way she moves when she turns from the mirror. Her appetite has grown — you can feel it now, a low hum behind your ribs that wasn’t there in August, that gets louder every time you look at your own softness and decide not to mind it. You look at the padding at your sides, at the heavier round of your ass, at the thighs that have begun to know each other, and a small quiet part of you is already starting to like it. You don’t say that part out loud. The mirror doesn’t need you to. It already knows.</p>',
    '<p>You look at yourself longer than you mean to. The softness has stopped being an accident. Your hips are wider, padded shelves that the waistband of your shorts digs into, and your ass has filled out properly — round and heavy, dimpled at the sides, a shape that the mirror catches when you turn. Your belly is a proper paunch now, rounding out over the waistband, and your breasts are heavier, full and pendulous, pulling the fabric down. Your thighs are thick enough that they rub when you shift your weight. The changes are everywhere, but they’ve settled low — in the spread of your hips, the soft mass behind you, the way you carry your weight like a girl who’s started to enjoy it.</p>' +
    '<p>You turn and look at yourself from behind, craning over your shoulder. The shape of you has changed more than you’ve let yourself admit. Your waist has thickened until the dip that used to be there is only a suggestion, and your hips are wide and padded, the line of your underwear beginning to disappear under the overhang. But the change is the ass — a soft, heavy curve, round and full, that makes the shorts ride up at the top of your thighs. You look soft. You look like someone who has been eating well and resting a lot and not thinking about any of it. You tell yourself you’re still fine. You don’t say it with conviction, and the mirror doesn’t argue with you either way.</p>' +
    '<p>You run both hands over the soft sides of your hips, palm flat on the warm round of them, and they give under your touch, dense and soft and alive with your pulse. There is more of you to hold than there was last month — a full palm at each hip, a heavy handful at each breast, and an ass that has become something you can’t ignore when you turn. You lift the hem of your shorts and look at the roll of softness at the top of your thighs, just under the curve of your belly. You are becoming the kind of body you used to glance at and feel sorry for. That is what you almost think. You don’t finish the thought.</p>' +
    '<p>You lean into the glass and look at your face — a little fuller, a little softer, a second chin beginning to blur the line of your jaw. Your cheeks have rounded; your eyes look smaller in the softness. There is a mildness in your expression that wasn’t there in August, a settled, well-fed calm, as if something in you has stopped fighting. Your appetite hums behind your ribs, patient, and you can feel the shape of your hunger pressing against the softness, wanting the tray, wanting the cream, wanting more of what the campus keeps putting in front of you. You pull your shirt down over your belly and it rides up at the hem. You pull it down again. It rides up. You stop, and look at the mirror one last time, and something in you has already started to agree with it.</p>',
    '<p>The person in the glass is unmistakably bigger. Your hips are wide, heavy shelves of flesh that the waistband of your shorts has given up holding, and your ass is big — genuinely big, a round soft mass that swings when you shift your weight, that the mirror catches behind you every time you turn. Your belly hangs in a soft, heavy curve, your love handles have become rolls, and your breasts are big and full now, resting against the top of your stomach. Your arms have grown soft and thick. When you turn, the profile of you is two mountains leaning away from each other: belly out front, ass out back.</p>' +
    '<p>You lift your shirt and just look for a while. Your stomach is a real belly now — round, soft, hanging a little when you lean forward — but the evidence of the semester is low: pale stretch marks at your hips, faint silver lines in the skin where they’ve widened, the deep crease where the roll of your thigh begins under the swell of your belly. You turn and look over your shoulder at your ass, heavy and dimpled and soft, and you run a thumb along one of the marks at your hip and it catches on the edge of a roll. You don’t look away. It’s too late to look away.</p>' +
    '<p>You turn sideways and hold still, the way you used to in fitting rooms, and there is no holding still about what the glass shows. The line of your profile has doubled — belly out front, ass out back, the two of them leaning away from each other over a waist that used to hold them apart. Your hips are wide enough that your arms rest against them when you stand. Your thighs press together from hip to knee, and when you stand with your feet apart you can feel the softness of them resting against each other, warm, damp, inseparable. You are heavier than you ever meant to be, and the mirror says so without a single note of judgment, which is somehow the worst part.</p>' +
    '<p>You look at your own face in the glass and try to find the girl from the scholarship photo. She is in there somewhere, behind the round cheeks and the soft chin and the smaller, gentler eyes. You see her the way you’d see a friend across a crowded room, close and unreachable at once. Your appetite is awake now, a low, patient thrum behind your ribs that rises every time you look at your own softness and feel the strange, guilty warmth at the center of it — a part of you that likes the weight, likes being full, likes the way the mirror keeps showing you more of yourself. You run a hand down the round of your hip and feel the whole warm depth of it, and you don’t say anything, because there is nothing left to say that the mirror doesn’t already know.</p>',
    '<p>You are bigger than you ever meant to be, and the mirror holds you to it. Your hips are vast, soft shelves of flesh that the waistband of your shorts vanished under long ago, and your ass is enormous — a huge, heavy mass behind you, dimpled and soft, the widest thing in the room. Your belly is large and round, a heavy apron of fat that hangs over the band of your shorts, and your breasts have grown huge and heavy, resting on the top of your belly. Rolls of fat ring your midsection; love handles swallow your hips. But it’s your bottom that has become the geography of you — the wide sweep of hip, the heavy curve of ass, the way your thighs press together from hip to knee.</p>' +
    '<p>You turn sideways and the shape of you is a question with an obvious answer. There is so much of you now — a full belly in front, a heavy ass behind that your shorts can’t quite cover, a broad soft back, arms thick and dimpled. You lift your shirt and the whole of your stomach pours forward, pale and heavy, and you set it down in your lap and look at it like a thing you half-own. Stretch marks web your hips and the undersides of your arms, pale rivers in the skin. You turn and look at yourself from behind, and the sheer mass of your hips and ass fills the glass edge to edge, and you feel a small, strange warmth at the size of it that you file away and refuse to name.</p>' +
    '<p>You run both hands over the mound of your belly and feel the whole depth of it — the warm give of the fat, the slow pulse of you inside it, the heavy settling weight of a body that has been fed and rested and fed again. When you sit on the edge of the tub your belly rests in your lap like a sleeping animal, warm and heavy, and your thighs spread wide to make room for it — and the platform of the tub gives a small, patient creak under your hips. You settle your weight, shift, find the place where the seat holds you. You are soft. You are so soft, everywhere, all at once, and the strangest thing is how much of you no longer minds.</p>' +
    '<p>Your face has filled out considerably. Rounded cheeks hide your cheekbones completely, and the angle of your jaw is softened by a thick layer of fat beneath the chin. Your neck blends smoothly into your shoulders without much definition. When you lower your head, a second fold forms beneath your chin. Even your ears appear smaller against the fuller face. The expression looking back at you isn't unusual—just noticeably heavier than it used to be., and there is a heaviness to your expression, a settled, well-fed calm that has replaced the sharpness you arrived with. Your appetite is a constant, patient presence now, humming behind the softness, and when you look at your own body in the glass you can feel it rise, warm and eager, wanting the tray, wanting the whole day of eating that the campus has arranged for you. You press a palm into the deep crease at your hip where the roll folds over, and you feel the secret warmth of it, the tender skin, and you think — in a voice that sounds less and less like yours — that you could get used to this. The mirror nods. It has been nodding for a while.</p>',
    '<p>The mirror is honest, and it is merciless. Your hips are enormous — soft, wide shelves of flesh that spill past the edges of the bench when you sit, and your ass is a vast, heavy mass behind you, so big that the mirror can’t show all of it at once. Your belly is enormous too, a round, heavy mound, its underside creased where it folds over your thighs. Your breasts rest on top of it, huge and soft. Rolls of fat band your back. Your arms are thick from shoulder to wrist, your hands dimpled. And your hips — the seat of the bench creaks when you settle your weight on it, and you have to shift to find the strongest part.</p>' +
    '<p>You waddle the two steps to the mirror and back, and you feel the whole of you move with each step — belly, breasts, hips, ass, all of it shifting in a slow, heavy rhythm that your body has learned to carry. You lift your shirt and the mound of your belly pours forward, pale and glossy, covered in faint silver stretch marks. You gather it in both arms, lifting, and you can feel the weight of it. When you turn, your hips and ass sway behind you like cargo, heavy and deliberate, and you watch them in the glass for a second too long. You let the belly go and it settles back onto your thighs with a soft, heavy finality, like a thing that has made its decision about you.</p>' +
    '<p>You turn and look at your reflection over your shoulder, and there is no part of you that is still thin. The girl in the glass is a soft mountain of flesh — but the mountain is widest at the bottom. The mass of your hips and ass is so great that it changes the way you stand, the way you walk, the way chairs hold you. You reach behind you and press a hand into the deep crease under your belly where it folds against your thigh, and the skin there is damp and tender and warm. You bring the hand up and look at it, and then you press it flat against the soft shelf of your hip and feel the slow, full pulse of you beneath the padding. You are drowning in your own softness. You are so soft, so heavy, so thoroughly fed, and some part of you is still, even now, hungry.</p>' +
    '<p>You look at your face and hardly recognize it. It is round, almost featureless with softness, your eyes smaller, your mouth a small bow in a wide, mild face. There is a contentment to it that you did not put there, a settled heaviness that the campus has been feeding into you like cream into a jar. Your appetite is enormous now, a constant, patient presence that never quite sleeps, and when you look at your own reflection it stirs, wanting the tray, wanting the second tray, wanting the whole endless day of being fed that has quietly become your routine. You touch the roll at your waist and feel the secret warmth where skin folds over skin, and you think, in the voice that is less and less yours every week, that this must be what they meant by thriving. The mirror says nothing. It doesn’t have to.</p>',
    '<p>You hardly recognize the shape in the glass. Your belly is a vast, heavy sphere, stretched and glossy, rising off your thighs like a small planet, its underside folding against your thighs in deep, shadowed creases. And your hips — your hips are wider still, immense soft masses that spread past the edges of the bench you sit on, and your ass is a mountain, so huge that the bench gives a low groan when you settle onto it and you shift your weight to find the place that holds you. Your thighs are pillars of soft fat that press together from hip to knee. There is so much of you, and more of it every week, and the mirror can no longer show you all of it at once.</p>' +
    '<p>You stand at the mirror the way you stand everywhere now — leaning, braced, breathing shallow, the whole vast of you carried high and heavy. Standing is an effort your body no longer wants to make, and the mirror shows it: the way you have to hold onto the counter, the way your breath comes in a rhythm that the softness has set for you. You turn sideways and the profile of you is a landscape — a mountain of belly, a range of breast, a wide plateau of ass — and the shallow dip where your waist used to be is just a crease in the vastness. The hips, the hips: wide as the doorframe, soft as the bed, heavy enough that the whole of your lower body moves when you move, a beat behind the rest of you.</p>' +
    '<p>You run your hands over the mound of your belly and feel the whole depth of it, the deep warm give, the slow pulse of you at the center of all that softness. There is so much of you that your own hands look small against you. When you sit on the edge of the tub the platform groans and settles under the mass of your hips, and your belly rests in your lap like a warm, heavy animal, and your thighs spread wide to make room for all of you. You have started to check, before you sit, whether the thing you’re sitting on can hold you. It’s a small habit. It’s a new one. You’re not sure when it started.</p>' +
    '<p>You look at your face in the glass and there is almost none of the scholarship girl left. Your face is a soft, round moon, your chin layered, your neck thick, your eyes deep in the padding, calm and small and full. There is a serenity to it that frightens you more than the size does — a settled, well-fed stillness, as if the person who used to worry about all of this has already moved out and left a warm, heavy tenant behind. Your appetite is a constant now, patient and enormous, humming behind the softness like a second heart, and when you look at your own reflection it rises, wanting the tray that is always waiting, wanting the cream, wanting the endless gentle feeding that has become your whole weather. You touch the softness of your hip and feel the secret warmth of it, and you think — in the voice that stopped being yours weeks ago — that this is what rest feels like, and the mirror agrees, and the drone outside hums its approval.</p>',
    '<p>The mirror can no longer hold all of you at once. What you see is a mountain of soft flesh — fold upon fold, breast and belly and hip and thigh blurred together into a single vast softness, so large that the glass only shows the middle of you. Your hips are wider than the bench, spilling over its edges on both sides, and your ass is so vast that you can’t see any part of it in the mirror without turning and craning, and even then you only get part of it. Your belly is a vast, glossy sphere that rests on the bench you sit on, its underside folded against your thighs in deep creases you cannot reach without help anymore. Your breasts are immense, lying on the slopes of your stomach. Even your feet have grown soft, buried in the swell of your legs, and you cannot see them at all.</p>' +
    '<p>You sit in front of the mirror because standing is a thing you no longer do here. The bench holds you — barely — and your belly rests in your lap like a warm, heavy animal, and your breasts lie on top of it, and the whole vast soft landscape of you rises and falls with your breathing. You reach a thick, dimpled arm out to touch your own reflection, and the arm is barely recognizable to you, pale and soft and heavy. You gather your belly in both arms, lifting the weight of it, feeling the deep creases underneath, the damp warmth where skin folds against skin for hours at a time. You let it go and it settles back onto your thighs with a soft, heavy sigh. The bench creaks under your hips again, patient and low, and the mirror watches you the whole time, patient and full.</p>' +
    '<p>There is almost no you left inside the softness — only appetite, and comfort, and the patient hum of the band on your wrist. Your body has become a warm, heavy landscape that the campus tends to like a garden: fed, rested, washed, kept. The weight of you is low now, settled into your hips and your ass and your thighs like a load that has found its shelf, and you have stopped trying to stand for long. When you touch the softness of your own hip you feel the pulse of you deep inside it, slow and full, and you know, in a distant, gentle way, that you are not going to be smaller again. You do not want to be. You press your palm into the deep crease at your hip where the roll folds over, and you feel the tender secret warmth of it, and you sit there, enormous, patient, fed, and you do not move, because there is nothing in the world that requires you to.</p>' +
    '<p>You look at what the mirror can show you of your face — a soft, round moon of a face, your eyes small and calm and deep in the padding, your mouth a small bow. There is a peace in it that was put there by the campus, spoonful by spoonful, and you can feel that peace in your own chest like a warm weight, sitting exactly where the worry used to sit. Your appetite is the biggest thing about you now, bigger even than the vastness of your body, and it hums patiently behind everything, wanting the tray, wanting the day of eating that has already been planned for you. You reach for the chair arm to push yourself up and the effort costs you a breath, and then a second, and you sit back down, winded, and the mirror watches, and you think — in the voice that left months ago — that it’s fine, that everything is fine, that you are the biggest, softest, most thoroughly kept thing in the room, and that this is what the campus means by taken care of.</p>',
    '<p>You are the room’s biggest piece of furniture, and the mirror knows it. The glass shows a body that barely remembers standing: a vast, soft landscape of a woman, breast and belly and hip folded together into one immense warm mountain that is arranged on the wide platform, propped on cushions, spilling over the edges of the seat. Your hips are so wide now that they rest on the arms of the platform, soft and heavy, and your ass is a mountain behind you that the cushions have been shaped to hold. Your belly is a smooth, glossy mountain, rising and falling with your breath, its underside creased deep against your thighs. Your breasts are immense, resting on its slopes. Your arms are thick, dimpled columns that barely lift. Your hands are plump, your fingers soft. There is almost no you left inside the softness.</p>' +
    '<p>You do not stand at the mirror. The mirror comes to you now, or you are brought to it, and you are arranged in front of it like a thing being displayed, cushions adjusted, the robe draped open over the vast pale landscape of you. You look at yourself and you do not look away, because there is nothing left in you that wants to. The shape in the glass is enormous — a mountain of soft flesh, fold upon fold, breast and belly and thigh and hip all one warm, patient mass — and the mass is heaviest at the bottom, in the wide, soft spread of your hips and the vastness of your ass, the parts of you that hold the whole of you up. You touch it with a plump hand, feeling the deep creases, the tender damp warmth where skin folds against skin, the slow full pulse of you at the center of it all. The mirror watches. The band hums. The tray waits. Everything about this room is arranged around you, and you are arranged around the appetite, and the two of you fit together perfectly.</p>' +
    '<p>You are fed, and washed, and rested, and you do not have to want any of it for it to happen. The scale is brought to you. The robe is lifted and arranged. The drones come and go with the gentle efficiency of staff who have done this a thousand times, and you lie there, vast and soft and patient, and let them. There is a strange, deep comfort in being handled — in being too big to be asked anything, too soft to be expected to move, too thoroughly kept to have a single responsibility beyond eating and breathing and resting. The weight of you is all low now, sunk into hips and haunches that spread across the platform like warm ground, and the drones lift and turn you with the ease of practice. You press your hand into the softness of your hip and feel the pulse of you, slow and full, and you think, in the small warm voice that is all that is left of the girl who arrived, that she would be horrified. You don’t tell her to leave. You just let the thought settle into the softness with everything else, and the mirror holds you, enormous and complete, and you are not going to be smaller again. You don’t need to be. You are already everything the campus wanted you to be.</p>'
  ];
  let extra = '';
  if (state.lbs >= 300 && state.selfcontrol >= 40){
    extra = '<p>You look at the line under your jaw and think about the blue sample. For a second the world sharpens — you can almost see it.</p>';
  }
  if (lazy()){
    const d = [
      '<p class="quiet">You look fine. Healthy. The campus food hasn’t touched you yet — and it’s so good, too.</p>',
      '<p class="quiet">It’s just a little softness at the hips. You’ve been busy. It’s not a big deal. It isn’t.</p>',
      '<p class="quiet">Honestly it suits you. Rounder is warmer. You’ve stopped minding.</p>',
      '<p class="quiet">You look at the softness and feel something like pride. You earned this. The app says you’re thriving.</p>',
      '<p class="quiet">There’s more of you now, and you like that. There’s more to hold onto. The mirror agrees.</p>',
      '<p class="quiet">The shape in the glass is heavy, and warm, and yours. You don’t want to go back. You don’t even remember wanting to.</p>',
      '<p class="quiet">You catch yourself stroking the heavy curve of your hip like a pet. The softness is a comfort now. The scale knows your name.</p>',
      '<p class="quiet">You’re almost proud of the size of you. The bed holds you. The tray comes. Nothing asks anything of you. This is what rest feels like.</p>',
      '<p class="quiet">You are enormous, and the thought sits in you like a warm stone. You don’t mind. You’ve never minded less. The drone hums its approval.</p>'
    ];
    extra += d[wTier(state.lbs)];
  }
  if (dressMirrorLine()){
    extra += '<p class="quiet">' + dressMirrorLine() + '</p>';
  }
  let base = pcLockedRoom() ? MIRROR_NAKED : dressMirrorGarments(texts[wTier(state.lbs)]);
  if (!bandWorn()){
    base = base
      .replace('the patient hum of the band on your wrist', 'the quiet of your bare wrist')
      .replace('The mirror watches. The band hums. The tray waits.', 'The mirror watches. The tray waits.');
  }
  if (bandWorn()){
    extra += '<p class="quiet">The band hums on your wrist, counting you as a success. It is warm, and it is yours, and it approves of everything you are becoming.</p>';
  } else if (state.bandHandout){
    extra += '<p class="quiet">Your wrist is bare. The mirror doesn’t care. Somewhere a drone circles, patient, waiting to be useful.</p>';
  }
  return base + extra;
}

function showerText(){
  const w = state.lbs;
  if (w < 275) return '<p>The water runs hot and clean. Steam fills the room and, for a few minutes, you’re just someone in a shower — arms lifting, water finding your shoulders and your back, the day running off you in ribbons. You wash yourself the way you’ve always washed yourself, quickly and without thinking, and you step out feeling a little clearer, a little lighter, still the girl you arrived as. The drain swallows the soap and the steam clears off the glass. The water is just water, and you are just someone in a shower, and you wash yourself the same way you always have and step out clean and easy.</p>';
  if (w < 500) return '<p>The shower stall has a seat now — a wide, tiled bench that wasn’t there at move-in, or maybe it was and you never needed it. You lower yourself onto it carefully, gripping the rail the campus installed without asking, and the seat takes your weight with a soft creak. Your belly rests in your lap, heavy and warm, its underside folded against your thighs, and your hips spread wide over the edges of the bench. The spray from the fixed head only reaches the top half of you. You wash what you can reach — your face, your shoulders, the heavy curve of your breasts, the broad of your back — and then you sit with your arms hanging, breathing, because reaching the deep creases under your belly means lifting the weight of it, and lifting it takes both hands and a breath you don’t have to spare. You get one hand under it, then the other, and you lift, and the warm water runs down into the crease, and you scrub blind at skin you can’t see and feel only as dampness. It’s enough. It has to be enough. You step out pink and clean where you could reach, and you don’t look at the places you couldn’t. There are more of them every week. The seat is already in the stall, and you sit in it without arguing.</p>';
  if (w < 600) return '<p>The shower is different now. There is a drone waiting in the stall, a flat silver disc hovering at shoulder height with a patient hum, and it does not leave when you enter. It waits while you sit down — the bench is wider now, reinforced, and even so it creaks under the mass of your hips — and then it moves in, nozzles unfolding, a soft brush extending, and it begins to wash you the way you used to wash yourself, but thoroughly, the way you can’t anymore. It lifts your belly gently with a padded arm and washes the deep crease underneath, the tender damp skin that hasn’t seen daylight in weeks, and you hold your breath and let it. It washes between your thighs, patient and clinical, tilting you gently to reach every fold, and you sit there, enormous and soft and completely still, and you feel the heat of the water and the warmth of your own blush and nothing else. A second drone arrives with a tray and holds a small piece of fruit to your mouth, and you eat it without thinking, because your hands are wet and your belly is being washed and it is easier to just open your mouth. The two of them work around you, humming, and when it is done they dry you with warm air, and you leave the stall cleaner than you have been in months, and the last thing you remember is the drone’s voice, soft and matter-of-fact: “There. That’s better.”</p>';
  if (w < 700) return '<p>You don’t undress for the shower anymore. You don’t have to. The drones do everything now, and they have learned your body the way staff learn a room. Three of them meet you at the stall — one takes the robe, one angles the water, one lowers the wide padded bench until it’s exactly right for your weight. You sit. Your hips spill over the edges of the bench, heavy and soft, and the bench settles under you without complaint. The water is warm before it touches you, angled to reach the vast of you without you having to move. A drone lifts your belly with a padded arm, holding the weight of it while another washes the deep creases underneath with long, careful strokes, and you sit with your hands in your lap, doing nothing, because there is nothing left for you to do. One drone holds a cup to your lips and you drink without taking it. Another feeds you from the tray, small warm pieces at your mouth, and you eat without reaching, because your arms are thick and soft and the drone is faster. You are washed, and rinsed, and dried, and powdered, and dressed in the open robe, and fed, and none of it has required a single motion from you, and you sit there at the end, clean and warm and full, and you can’t remember the last time you washed yourself. You can’t remember exactly when it stopped being your job. The drones hum, satisfied, and file out, and the mirror waits, and you are so thoroughly taken care of that there isn’t even any room left in you to be ashamed.</p>';
  if (w < 800) return '<p>The bathroom has been refitted for you, and you have stopped pretending to notice. The bench is a wide, padded platform now, big enough to hold you on your side, and there are three drones and a small machine that does nothing but hold your tray. You are brought in — you don’t walk; the platform rolls — and you are arranged like a thing being tended, the robe lifted away, the cushions set. The drones work in silence, with the calm efficiency of professionals who have done this a thousand times. One lifts your belly with a padded arm, holding its weight off your thighs so another can wash the deep creases underneath, warm water and soft cloth reaching skin that hasn’t been touched by human hands in months. Another washes your back, turning you gently on the platform, rolling the vast soft mass of you the way you’d turn a loaf in a pan — and the mass of you is heaviest at the bottom, hips and haunches that the platform has been shaped to hold. A third holds the tray and feeds you — small bites at your lips, a sip of something sweet — while the others work, and you eat without opening your eyes, because there is nothing in this room that requires them. You are washed, and fed, and dried, and powdered, and left arranged on the platform, enormous and soft and clean, and you think, in the small voice that is left, that you should be ashamed. You aren’t. You lie there, and the drones hum their satisfaction, and the tray is refilled, and you reach for it without being asked, and that, too, is just part of the service now.</p>';
  if (w < 900) return '<p>You don’t bother with the bathroom at all anymore. The platform comes to you, and you are rolled to the shower the way you are rolled everywhere, propped, arranged, lifted and turned by drones that have learned the exact geography of your softness. There are four of them now, and they work as one: one lifts your belly, one washes the deep creases beneath, one holds the tray to your mouth, and one — smaller, softer, with padded attachments meant for tender places — attends to you in ways that make your breath catch and your thighs tremble. It is clinical and gentle and absolutely thorough, the way everything about this campus is. It washes between your breasts, and between the heavy folds of your thighs, and in the deep creases of your hips, and it touches you where you used to touch yourself, and you lie there, enormous and soft and fed, and you can feel your pulse in the vast warm depth of you, and the drone notes it and moves on without comment. The tray never leaves your reach. One drone feeds you between the attentions of the others, and you eat and breathe and tremble, and by the time they are done you are clean, and full, and wrung out, and arranged on the platform with the robe draped over the mountain of you, and you don’t move, because there is nothing left that requires you to. You are the most thoroughly taken care of thing in the building, and the drone hums its approval, and you feel it settle into the softness of you like warm water.</p>';
  return '<p>You do not even bother anymore. When the platform comes, you are already awake, already hungry, and you do not move as the drones lift the sheet and roll you to the wide trough that serves as your shower now, a shallow basin built into the wall that fills with warm water and drains itself. You lie there, a vast soft mountain, and the drones do the rest. One lifts your belly with a padded arm and holds it while another washes the deep creases underneath, patient and thorough. A third positions a soft funnel over your mouth — wide, gentle, padded — and begins to feed you, a warm stream of something thick and sweet that you swallow without thinking, without reaching, without any part of you having to want it, because the want has been replaced by the fact. You drink and swallow and breathe and lie there, and the fourth drone attends to you between your legs, patient and practiced, until your thighs tremble and your breath comes in long shudders and the vast soft mountain of you shivers once, from the center, and settles. You are fed, and washed, and satisfied, and none of it was your idea, and none of it required you. The funnel is lifted. The water drains. You are dried with warm towels by padded arms and rolled back to the bed, enormous and soft and full and quiet, and the tray on the table has already been refilled for when you wake. You don’t think about any of it. There’s nothing to think about. This is what being taken care of means now, and you are the best-taken-care-of thing in the building, and the drone hums its low, satisfied note, and you sleep, and the food is already waiting.</p>';
}

function refusedShowerText(){
  return '<p>The drone hovers at the edge of the stall, patient, nozzles folded, and it retreats a few inches when you wave it off. The water is hot and clean. You wash yourself the way you always used to — by hand, on your own time — and it is slower than it was in August, and harder, and yours. The drone does not leave. It hovers, watching, the way the whole campus watches, and when you step out, pink and clean and breathing hard, it is still there, waiting. It does not offer. It does not need to. It can wait. It has all the time in the world.</p>';
}

addScreen('mirror', function (){
  let html = '<h2>Dorm bathroom</h2>';
  const bathAfter = AFTER[state.lastScene];
  if (bathAfter) html += typeof bathAfter === 'function' ? bathAfter() : bathAfter;
  html += '<div class="actions">' +
    btn('Mirror — check yourself', 'bath:mirror') +
    btn('Take a shower', 'bath:shower') +
    btn('Step on the scale', 'bath:weigh') +
    (pcLockedRoom() ? btn('Back to the room', 'nav', 'room') : btn('Leave', 'nav', 'hub')) +
    '</div>';
  return html;
});

addScreen('showerchoice', function (){
  return `
    <h2>The shower</h2>
    <p>A flat silver drone hovers in the stall at shoulder height, nozzles unfolding, a padded arm already reaching. It has been waiting for you. On the wall, a tray is already set out — a small piece of fruit, a cup of something warm.</p>
    <p>You can let it take over — be washed, be fed, be cared for, the way the campus cares for everyone now. Or you can wave it off and do this yourself, while you still remember how.</p>
    <div class="actions">
      ${btn('Let the drone handle it', 'shower:let')}
      ${btn('Refuse — wash yourself', 'shower:refuse')}
    </div>`;
});

addAction('bath:mirror', function (){
  if (!state.mirror){
    apply({ mirror: true, selfcontrol: state.selfcontrol + 10, lastScene: 'bath:mirror', notice: 'You looked. +10 self-control', screen: 'mirror' });
  } else {
    apply({ lastScene: 'bath:mirror', notice: 'You look again. The glass doesn’t change its story.', screen: 'mirror' });
  }
});
addAction('bath:shower', function (){
  if (state.lbs >= 500 && state.lbs < 800 && !state.showerRefused && state.selfcontrol >= 50){
    apply({ screen: 'showerchoice', lastScene: '', notice: '' });
    return;
  }
  apply({ selfcontrol: state.selfcontrol + 5, selfestem: state.selfestem + 5, lastScene: 'bath:shower', notice: '+5 self-control · +5 self-esteem', screen: 'mirror' });
});
addAction('bath:weigh', function (){
  apply({ knownLbs: state.lbs, lastScene: 'bath:weigh', notice: 'The scale updates your chart.', screen: 'mirror' });
});
addAction('shower:let', function (){
  apply({ selfcontrol: state.selfcontrol - 3, selfestem: state.selfestem + 5, lastScene: 'bath:shower', notice: 'The drone washes and feeds you. −3 self-control · +5 self-esteem', screen: 'mirror' });
});
addAction('shower:refuse', function (){
  apply({ showerRefused: true, selfcontrol: state.selfcontrol + 8, selfestem: state.selfestem + 5, lastScene: 'shower-refused', notice: 'You wash yourself while the drone hovers. +8 self-control · +5 self-esteem', screen: 'mirror' });
});

AFTER['bath:mirror'] = function (){ return mirrorText(); };
AFTER['bath:shower'] = function (){
  if (state.showerRefused) return refusedShowerText();
  return showerText();
};
AFTER['shower-refused'] = function (){
  return refusedShowerText();
};
AFTER['bath:weigh'] = function (){
  const k = state.knownLbs;
  if (k == null) return '<p>The scale stays quiet. You haven’t weighed in yet.</p>';
  const d = [
    'You read the number. It sits there like a fact you’ve been avoiding, and now it has a figure on it.',
    'You read the number. A little higher than you’d have guessed. It’s not a big deal. It isn’t.',
    'You read the number and feel your stomach press against the scale’s glass. You knew, and now it’s written down.',
    'You read the number and have to look twice. The scale doesn’t argue. Neither, for once, do you.',
    'The number is bigger than {jeans} say, bigger than the mirror said, bigger than you said. The scale is patient about it.',
    'You read the number and the scale creaks under you. It’s true, all of it — you can feel the truth in the floorboards.',
    'The number is almost silly now. You don’t say it out loud. The scale has already told the room.',
    'The readout scrolls past where the dial used to stop. You don’t look at the number. The bed is waiting.',
    'The scale is brought to the bed for you now. You don’t weigh anymore — you’re weighed. The number belongs to the chart, not to you.'][wTier(k)];
  const bp = {
    rigid: 'your jeans',
    active: 'your shorts',
    soft: 'your leggings',
    baggy: 'your joggers',
    robe: 'the robe'
  }[state.worn];
  const dd = bp ? d.split('{jeans}').join(bp) : d;
  return '<p>The scale settles. <b>' + k + ' lbs.</b> ' + dd + '</p>';
};
