'use strict';

const PC_MORN = [
  '<p>The light is grey-blue and thin, and you wake flat on your back, hands folded on your stomach the way you always sleep. Your stomach is flat, the skin smooth, and through the cotton of your tank top you can feel the ribs under it, each one distinct. Your breasts are small and high on your chest, barely pressing against the fabric. Under the sheet you can feel the shape of yourself — the inward curve at your waist, the modest round of your hips, thighs that sit apart when you lie relaxed. You breathe in and nothing strains; you breathe out and the bed is exactly your shape and no larger.</p>',
  '<p>You sit up in one motion and your feet land flat on the cool floor. You stand without a wobble, no soft roll of anything following you upward. In the little mirror over the desk you can see the whole length of yourself — average height, average frame, the same girl from the photo in your file. Your jeans hang loose enough to pull off without unbuttoning. Your shirt is the one from move-in and it fits the way it did in August. In this grey light it still does.</p>',
  '<p>Dressing takes under a minute. The jeans button in one pull, the waistband sitting flat against the skin with no fold of flesh over it. The shirt goes over your head without catching on your shoulders. The bra hooks in a single pass behind your back and the cups sit level, the underwire a finger’s width below the breast. You run a hand down your own front and feel the flat of your stomach under the cotton, smooth, no crease at the navel. You are dressed, and the whole of it took less than a minute.</p>',
  '<p>You stand at the dark glass of the window and catch your own reflection — a thin girl in a grey tee and loose jeans. The line from your shoulder to your hip is straight; the shirt falls from your chest without lifting at the hem. You pull your hair back and check your phone. The flat line of yourself in the glass holds no surprises. You grab your bag and head out.</p>',
  '<p>Standing at the sink you see yourself fully: the flat stretch of your stomach between the hem of your shirt and the top of your jeans, the navel a small shallow oval, the neat small weight of your breasts high on the chest. You pull your hair back and your wrists look almost delicate in the grey light, the knuckles visible when you flex your hand. You zip your jeans, check your phone, and go.</p>',

  '<p>You wake on your back, and the first thing you feel is the weight — low, pressed against the mattress behind you. Your hand finds your hips before it finds your stomach, and there is more of them than there was at move-in: a new padding at the sides, a softness that was not in the photo in your file. Your stomach is still flat, mostly; the change has settled lower, in the spread of your hips and the new roundness pressing against the sheet at the top of your thighs. Your fingers press in and the flesh gives, slow, and settles back.</p>',
  '<p>Getting up takes one extra beat. Not a struggle — just a beat. You swing your legs over the edge and push off, and the weight settles with you, low over the waistband of your sleep shorts. When you turn toward the mirror you see it: your hips have filled out, just slightly, a softness that rounds the line of you from behind. The jeans you slept in yesterday are snugger at the hip when you pull them on; you have to rock your hips side to side to get the button over, the waistband cutting a shallow red line into the new padding above it.</p>',
  '<p>The jeans still button, but by the time they are on a red line runs across the softness above your hips where the waistband pressed. Your shirt hangs looser over your ribs and a touch tighter at the hip, the hem catching on the padding at your sides when you smooth it. You stand in front of the mirror and pull the fabric flat, and the softness settles back into place at your sides as soon as you let go.</p>',
  '<p>You catch your reflection in the window glass as you turn to leave — a girl who is only slightly different, only a little rounder at the hips. You look at her for a second, at the new curve of her hip pressing against the fabric, the way the jeans pull across the seat, and you walk out into the morning.</p>',
  '<p>Before you leave you turn sideways in front of the mirror and hold still. There it is — the beginning. A softness at your hips that a week ago you’d have called a shadow, a roundness at the waist that shows in profile. Your thighs meet at the very top when you stand straight, the soft flesh pressing together in a warm seam, and the navel has begun to deepen, the walls inside a little less taut. You run a hand over the new curve of your hip, feel the flesh give, and pull the door shut.</p>',

  '<p>You wake slowly, the way you do now, surfacing through a few extra layers of sleep. Your hand finds your stomach before you’re fully awake, and there’s a little more of it under your fingers than there used to be — a gentle roundness, a soft shelf that wasn’t there at move-in. Your tank top sits a shade tighter over your ribs, and your breasts feel a touch heavier against the fabric, a little fuller at the bottom. Under the sheet your thighs press together at the top now when you lie on your back, and your hips have begun to spread, soft and wide, a new weight that settles low into the mattress.</p>',
  '<p>Getting up takes one extra beat. Not a struggle — just a beat. You swing your legs over the edge and push off, and your belly settles over the waistband of your shorts, a small round weight that wasn’t there in August. You stand, and your breasts shift inside your top, and your thighs rub once, briefly, when you turn toward the mirror. Your ass is a little rounder behind you than it was at move-in; you feel it in the way your shorts pull across it, the fabric cutting into the crease at the top of each thigh.</p>',
  '<p>The bra is the first thing that feels different. It hooks the same, but the cups are tighter, the underwire pressing into the softness over your ribs, and when you look down you can see the top edges of your breasts pressing up against the fabric, fuller at the bottom. The shirt hides most of it. The jeans hide the rest — the way your hips have padded out, the new softness that spills just slightly over the waistband at your sides. You stand in front of the mirror and pull your shirt flat over your stomach, and as soon as you let go the soft roundness settles back into place.</p>',
  '<p>You catch your reflection in the window glass as you turn to leave — a girl who is only slightly different, only a little rounder. You look at her for a second, at the roundness under her shirt, the way the hem rises over her belly, the new curve of her hips, and you walk out into the morning.</p>',
  '<p>Before you leave you turn sideways in front of the mirror and hold still. There it is — the beginning. A softness at your waist that a week ago you’d have called a shadow, and a matching roundness behind you, a curve at your hips that shows from the side. The navel is deeper now, the top edge beginning to fold inward when you sit. Your shirt pulls across your chest a little differently, and your hips settle with a low weight when you shift into them. You run a palm over the soft curve of your waist, feel the flesh move, and pull the door shut.</p>',

  '<p>You wake to the weight of yourself, and the weight is low. It’s the first thing you feel, half-asleep: the broad spread of your hips against the mattress, the heavy curve of your ass settling behind you, the press of your thighs together at the top. Your tank top has ridden up and your stomach is bare — a proper paunch rounding out over the waistband of your sleep shorts, the navel a deep round dimple in the middle of it. Your hips are wider than they were at move-in, a soft shelf of flesh that spills past the sides of your shorts, warm and heavy against the sheet.</p>',
  '<p>Getting out of bed is now a two-part motion. You push yourself up, let the blood settle, and swing your legs over the edge. Your belly settles forward over your thighs as you sit — but it’s your hips and your ass that catch the motion when you stand, a wobble that travels all the way down. Your thighs rub together now, the soft flesh pressing in a damp seam, and love handles spill over the elastic waistband of your shorts. Your ass, when you turn, is round and heavy under the cotton, dimpled at the sides, swaying a beat behind the rest of you.</p>',
  '<p>Dressing has become a negotiation. The jeans from the first week won’t button anymore, so you go for the stretchy shorts, and even those leave a red line where the waistband digs into the softness above your hips. The bra takes two tries — hook it, adjust, hook it again — and your breasts, fuller and heavier, press against the top of the cups. Your shirt is a size you’d have called too big in August. It fits now, snug around your middle and tighter at the hip. You look down and the hem rises over the curve of your belly when you reach for your phone, exposing a pale crescent of skin. You pull it down. It rides up again. You stop pulling.</p>',
  '<p>You get dressed slowly, moving with a lag between deciding and motion. You sit on the edge of the bed to catch your breath, and the mattress takes your weight with a small complaint. Your hips spill over the edge on either side, soft and heavy, and the waistband of your shorts has rolled down under the fold of your belly. Your breakfast is already on the tray by the door. You reach for it before you’re done with your shoes.</p>',
  '<p>You stand at the mirror a moment before you leave, hands on the soft sides of your hips. Your ass is big and soft behind you, heavy enough that your shorts have started to ride up into it, the fabric cutting into the flesh. You press a palm into the pad of your hip and it gives, deep and dense, the warmth of it under your hand. You pull the shirt down. It rides up again. You leave it.</p>',

  '<p>You wake up hungry. That’s the first thing — a hollow, pressing hunger already there before you open your eyes, sitting behind your belly. You wake to the weight of your own body surrounding you, more of you than there was at move-in — and most of it is low. Your hips are wide, heavy shelves of flesh pressing into the mattress, and your ass is genuinely big now, a soft, massive curve that the sheet has long since given up covering. Your thighs are thick, pressed together from hip to knee. There’s a belly too, a soft heavy curve that rests beside your hip, and the whole low, broad mass of you settles deep into the mattress.</p>',
  '<p>Getting up is a whole event now. You roll to your side — everything follows, slowly, in its own time — push up on one elbow, let the blood settle, swing your legs over the edge. Your belly hangs forward over your thighs when you sit, and your hips spill over the edge of the mattress on either side of you. You stand, and your body jiggles, settles, finds its balance a little later than it used to. Your ass is heavy and dimpled, swaying behind you with every step, and your thighs rub together as you waddle the two steps to the dresser. You can’t see your own toes anymore without leaning forward and over the swell of your belly.</p>',
  '<p>Dressing takes a while, and you’ve started budgeting for it. The underwear has to be pulled up under the overhang of your belly, and it leaves red creases where it holds your hips. The leggings are the stretchy ones, and even they creak across the widest part of your ass when you pull them up; the waistband rolls down over the softness above your hips no matter how you tuck it. You dress sitting down now, because standing for the whole thing makes you breathe hard. The shirt is a man’s tee you stole from the laundry pile, and it covers your stomach only if you don’t move. You stand, breathe, and the shirt rides up over your belly without being asked.</p>',
  '<p>You run a hand over your own soft hip and you feel it — deep, yielding — and the hunger behind it, already pressing up into your throat. When you sit back down on the edge of the bed the springs give a low groan, and you shift your hips to find the strongest part of the mattress, the flesh settling and spreading around the frame. You sit on the edge of the bed, breathe, and reach for the tray by the door before your feet have even thought about the floor.</p>',
  '<p>You notice, this morning, that your sleep shorts have a crease across the front where the waistband folds under the weight of your belly — and that your ass has outgrown them entirely, the seams pulled tight over the heavy curve of it. Your hand finds your hip when you sit up, palm flat on the soft shelf of it, and the flesh gives under your palm. You sit there a moment, hand on your hip, and the hunger is already awake behind it, pressing at the wall of your belly.</p>',

  '<p>You wake to the smell of food — there’s always the smell of food now, drifting in from the tray by the door even before you’re awake. You wake to the size of yourself, and the size of you lives low. Your hips are vast, soft shelves of flesh that spread across the mattress, and your ass is enormous — a huge, heavy mass pressing into the mattress, the sheet pulled taut over it. Rolls of fat band your back and sides, and it’s your bottom that holds the true weight of you: the wide sweep of hip, the deep crease between your thighs, the place where you sit that has begun to outgrow every seat on campus.</p>',
  '<p>Getting out of bed is a production. You have to rock yourself sideways, grab the bed frame, heave — and the bed gives you up slowly, mattress groaning, your whole body following your belly down and forward until you’re sitting on the edge with your feet barely reaching. Your hips spill over the edge of the mattress on both sides. Standing takes a moment and a breath. Your thighs are thick columns of soft fat that press together from hip to knee, and when you stand you waddle — wide, deliberate steps, your ass rolling heavy behind you. Your feet have started to disappear behind the swell of your body. You have to lean to see them.</p>',
  '<p>Dressing is the hardest part of the morning. The underwear goes up under the apron of your belly, and you have to lift the fat out of the way to find it. The leggings have to be worked up over the widest, heaviest part of you — you sit, you push, you roll your hips — and the waistband still rolls down under the weight of your belly. You sit on the edge of the bed to do it, and the bedframe complains, and your hips spread across the mattress. The shirt is enormous now, an XXL, and it fits. It fits, and there’s still a soft roll of belly visible at the hem when you sit.</p>',
  '<p>You sit on the edge of your bed to finish dressing, breathing between the small tasks, the hunger pressing up behind your belly. Your belly is enormous, resting in your lap, heavy — and below it, the seat of the bedframe has already given way to the mass of your hips, the mattress bowing under your weight. The room smells like grease and sugar. The tray is by the door, already waiting, already sized to you. You look at it, and your hand reaches for it.</p>',
  '<p>There is a moment, halfway through dressing, when you sit on the edge of the bed with one sock on and just breathe. The tray is by the door. Your hips rest across the mattress, and your ass — you can feel it, heavy and huge, the widest thing in the room. The lifting, the reaching, the breath you have to take before you bend — all of it takes longer every morning. You pull the sock on, you reach for the shirt, and the waistband of the leggings bites into the softness above your hips before you’ve even stood.</p>',

  '<p>You wake on your side with a loud burp, the sound escaping before you’ve even opened your eyes. Your body feels heavy against the mattress. Your enormous belly is pressed partly beneath you, its weight spilling forward and downward, while your broad hips and cellulite-laden ass sink deeply into the bed. Stretch marks run across your sides and lower belly, pale lines crossing the stretched skin.</p>',
  '<p>For a few seconds you lie there, breathing heavily. A tray from the night before is still sitting on the small table beside the bed, along with a half-open box of pastries. You reach over without sitting up, take one, and eat it slowly. Your lips smack softly between bites. You swallow, let out another burp, and reach for a second pastry before finally deciding to get up.</p>',
  '<p>You roll onto your back. Your belly shifts with you, a vast mass of soft fat rolling across your middle before settling heavily in place. You push yourself toward the edge of the mattress and let your legs drop to the floor.</p>',
  '<p>Getting upright takes effort. You plant your feet, brace your hands, and push. The mattress gives beneath you before you finally rise. Your fat rolls shift with the movement, and your enormous ass wobbles heavily behind you. You stand still for a moment, breathing hard, with the taste of food still in your mouth.</p>',
  '<p>The first steps across the room are slow. Your belly sways in front of you, while thick folds around your waist jiggle with every footfall. Your cellulite-covered thighs rub together as you walk, and the heavy flesh of your hips shifts from side to side. By the time you reach the dresser, you’re breathing deeply enough to stop and lean against it.</p>',
  '<p>After catching your breath, you turn toward the window. Your reflection appears in the glass, filling most of the space. From the front, your belly forms a huge rounded mass, with your navel sitting deep in the surrounding fat. Thick rolls gather around your waist and sides. Your breasts hang heavily above the curve of your stomach, while your arms have become thick and soft down toward the wrists.</p>',
  '<p>You turn sideways. Your belly projects far forward, while your enormous hips and cellulite-ridden ass extend behind you. There is almost no narrow point left at your waist; instead, several rolls of fat blend into one another around your middle. When you shift your weight, your whole lower body follows a moment later, the heavy flesh wobbling before settling.</p>',
  '<p>You turn away from the window and make your way back toward the bed. Each step leaves you breathing harder. Your thighs rub continuously, and the fat around your belly and hips jiggles with every movement. You reach the bed, turn carefully, and lower yourself onto the edge.</p>',
  '<p>Your hips spread heavily across the mattress as you sit. Your belly drops forward and settles across your thighs, forming soft folds beneath the weight. You reach toward the tray again and take another pastry. You chew, smacking your lips between bites, then swallow with a heavy breath and another small burp.</p>',
  '<p>You remain sitting there with the tray beside you, eating one bite at a time. Your belly rests across your thighs while your cellulite-covered ass stays sunk into the mattress. The folds around your stomach shift whenever you move, and your thick thighs remain pressed together beneath them.</p>',

  '<p>You wake by degrees, all of you coming into focus at once. The bed has molded to you entirely — you are not in it so much as part of it, a vast softness that the mattress has reshaped itself around. Your belly is a round glossy mound — but your hips are wider still, immense shelves of soft flesh that spread past the edges of the mattress, and your ass is a vast heavy mass that the bed can no longer hold separately. There is a lot of you. There is so much of you that the bed seems small, and the tray by the door is already being slid in.</p>',
  '<p>Getting out of bed is a decision you make carefully. You rock, you push, the bed groans, and for a moment nothing happens — and then you tip forward, enormous, and your feet find the floor and your whole body settles in one long, soft cascade. You stand, swaying, hands braced on the bed frame, your heart working, your breath loud in the quiet room. Your hips are so wide that your arms, hanging at your sides, rest against them. Your ass is a vast, heavy mass behind you, and you can no longer see your own feet at all.</p>',
  '<p>Dressing, at this size, is mostly a formality. The robe is the only thing that fits. Underneath, nothing else makes the journey: the underwear is gone, given up weeks ago; the bra is gone, your breasts too vast and heavy for any of it; the shorts are a distant memory. You sit on the edge of the bed to tie the belt, and the edge barely holds you — your hips spill over it, heavy and soft, and the springs have gone quiet under the settled weight. You wrap the robe around all of it and it doesn’t close. You tie the belt loosely over the place where your waist used to be. You sit on the edge of the bed, breathing. The tray is on the little table by your bed.</p>',
  '<p>You sit on the edge of your bed in your open robe, enormous and soft and hungry. The room is close, full of breathing. The tray is right there, on the little table by your bed, already sized to you. You reach for it before your feet even think about the floor. You eat, your belly pressing into your lap, and the drone hums at the door.</p>',

  '<p>You wake up already tired, and you wake up already hungry, and you wake up already the biggest you have ever been. The bed has given up its shape entirely — the mattress bowed to the exact enormity of your body. Your belly is vast, a smooth glossy sphere that rises off your chest — but your hips are the widest thing about you now, immense soft masses that spill over the sides of the bed, and your ass is a huge mass of flesh that the mattress has long since stopped trying to hold. When you breathe, the whole of you moves, slow and deep. You don’t try to move yet.</p>',
  '<p>Getting up takes the whole of your will, and some mornings it takes more than you have. This morning you manage it in stages: rock your weight, groan, get your feet under you — the floor feels very far away — push. The bed gives you up slowly, reluctantly, and you come upright in a long, soft cascade, sitting on the edge with your belly in your lap and your hips overflowing the mattress on both sides. Your feet barely reach the floor. You sit there a long time, breathing, hands braced on the frame, your heart working loud in your chest. The two steps to the dresser leave you winded, and you lean on it, belly pressing against the edge, and reach for the tray by the door.</p>',
  '<p>You no longer bother with dressing. Nothing fits. Nothing has fitted for months, and then the clothes themselves stopped — the robe is somewhere in the room, shed like everything else, and you are simply, entirely naked. Under the sheet there is only the enormous, soft, pale expanse of you. You don’t try for underwear. You don’t try for a bra. You don’t try for anything that used to be clothes. You lie there naked, fold upon fold of flesh, belly vast and glossy, the low, massive sweep of your hips spreading across the mattress, and the sheet rises and falls with the weight of your breathing.</p>',
  '<p>You don’t get up. The tray is right there, on the little table by your bed, already sized to you. You reach for it without getting up, your belly shifting against the mattress, and you eat, and the drone hums outside the window, and a second tray is already being slid through the door.</p>'
];
